### ISSUE TITLE
Create additional examples for each IWXXM product

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#1]
The existing set of examples cover a good amount of the model, but additional examples are needed for validation of the model and as samples for IWXXM developers.

Specific cases that are needed include a "normal" SIGMET, all status types for each report (correction, amendment, cancellation, etc.), and all other major report types.

This should be started after IWXXM 2.0 modifications are complete to ensure that redundant work is not performed.

ref: https://software.ecmwf.int/issues/browse/AVXML-1

Created:
    29/Sep/15 6:41 PM 

Reporter:
    Aaron Braeckel

**Comment by braeckel** [comment]
These new examples should include at least one COLLECT/bulletin example, preferably one for each product

**Comment by braeckel** [comment]
In TT-AvXML-6 it was agreed that specific examples needs should be identified.  @blchoy will add a COLLECT example with a single complex TAF or SIGMET

**Comment by braeckel** [comment]
The collect part of this issue was addressed in IWXXM 2.1.1RC1 with commit https://github.com/wmo-im/iwxxm/commit/20c4c6bc8dade6d71e1e0afe0e2299520c5cdb22, https://github.com/wmo-im/iwxxm/commit/05a9a44e452e3b7bb04d10da6918abe0b9bad597, https://github.com/wmo-im/iwxxm/commit/e22c3651081898796176a3711b2d9840a58af748, and a few others.

**Comment by braeckel** [comment]
We have created the iwxxm-translation repository (https://github.com/wmo-im/iwxxm-translation) for examples, as needed we can take some of these examples and include them in future IWXXM releases.  For the time being no specific action is needed and this issue is closed
