### ISSUE TITLE
Add TAC code mappings into the WMO Codes Registry

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#10]
To allow for authoritative translations between TAC and XML, it is necessary to be able to look up a code entry (such as http://codes.wmo.int/bufr4/codeflag/0-20-008/3) and have an explicit mapping to its TAC form ('BKN'). In earlier communications with WMO Codes Registry maintainers the conclusion was as follows:

“…labels from SKOS [1]; e.g. `skos:prefLabel` and zero or more `skos:altLabel` properties in addition to the existing `rdfs:label` property. RDF (& the registry itself) fully support provision of multi-lingual text. Additionally, for strings such as "BKN" we can add `skos:notation` [2] properties”

[1]: http://www.w3.org/TR/skos-primer/#seclabel
[2]: http://www.w3.org/TR/skos-primer/#secnotations

It is probably also necessary to document how IWXXM users might check this information and potentially provide a script to check and/or download them with the IWXXM release.

ref: https://software.ecmwf.int/issues/browse/AVXML-19

Created:
    29/Sep/15 9:21 PM 

Reporter:
Aaron Braeckel

**Comment by marqh** [comment]
I have investigated this issue and I do not think that there are currently published and authoritative translations between TAC an XML.

Whilst the registry can publish such information, doing so suggests that it is authoritative and that the authority is the WMO.

If we do not already have these translations, I do not think it is plausible for the task team to generate these, validate them and publish them in time for IWXXM 2.1

I think this requirement should be moved to IWXXM 3 to enable the work to identify and validate translations may be undertaken.

**Comment by blchoy** [comment]
I think this has been superseded by event:  We now have a tool to download the needed code tables in RDF format.  We are also moving from the un-maintained BUFR tables to 49-2 tables.  Further actions will be followed up in #37.
