### ISSUE TITLE
Runway state group clarification needed

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#101]
The TAC-to-XML-Guidance.txt states:

>  R99 (runway designator for runway state)
>   When a new runway state report is not available in time for dissemination of the METAR message, the previous runway state report will be repeated

This is not a explanation of how "R99" is to be encoded in IWXXM, unlike occurrences of "R88".  Perhaps its needless to say "99" is not a valid runway direction, but should we still encode 99 in <aixm:RunwayDirection> given there is no mechanism to signify 'from previous report'?

**Comment by blchoy** [comment]
A suggested implementation is as follow:
```
      <iwxxm:runwayState>
        <iwxxm:AerodromeRunwayState reportNotAvailable="true">
          <iwxxm:runway nilReason="http://codes.wmo.int/common/nil/inapplicable"/>
          ...
        </iwxxm:AerodromeRunwayState>
      </iwxxm:runwayState>
```

**Comment by mgoberfield** [comment]
Counter-proposal:

`      <iwxxm:runwayState>
        <iwxxm:AerodromeRunwayState fromPreviousReport="true">
          <iwxxm:runway nilReason="http://codes.wmo.int/common/nil/inapplicable"/>
          ...
        </iwxxm:AerodromeRunwayState>
      </iwxxm:runwayState>`

**Comment by jana-lachova** [comment]
When we go for one of the previous proposals (with indicator for previous report), we have opportunity to achieve both goals (historical errors are not repeated and TAC could be still translated to IWXXM 3.0)
- in case that correct runway is known (e.g. in case of data originator or in case translator knows previous reports), the correct runway can be fully provided, however it is still necessary to set `fromPreviousReport="true"` to indicate that no new observation or measurement of runway state was done
- in case that correct runway is not known `nilReason` can be used

**Comment by blchoy** [comment]
Changes checked in to 3.0.0RC2.
