### ISSUE TITLE
Runway designator with SNOCLO

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#103]
The case of a specific runway being closed due to snow, e.g. "R07/SNOCLO", cannot be represented in IWXXM 3.0.0RC1 or is not sufficiently obvious how it should be done. Ref: #48

**Comment by blchoy** [comment]
Sorry I am not familiar with SNOCLO, but the template does not seem to imply one can specify runway as R/SNOCLO overrides all elements including Runway Designator?

**Comment by mgoberfield** [comment]
My mistake then. I thought I found a 'real-world' example of such a case.

**Comment by blchoy** [comment]
Having said that, do you think there is a real need or future possibility to specify runway for SNOCLO?  I am not saying we are going to request a change in TAC, but nullifying iwxxm:runwayState is not the only way to represent SNOCLO; we may also use a boolean similar to iwxxm:cleared to indicate this status, and use schematron rules to mandate other elements to be empty when this is set.  In future when it has been decided to include Runway Designator for SNOCLO, we only need to change the schematron but not the XML.

But we still need to see if there is a foreseeable need for that (which is out of my knowledge unfortunately).
