### ISSUE TITLE
Issue with rule TAF.TAF-4 and TAF schema

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#104]
Under what circumstance would `<iwxxm:previousReportAerodrome>` be different from `<iwxxm:aerodrome>` ?   In other words, if you are amending, correcting or canceling a TAF, aren't `<iwxxm:aerodrome>` and `<iwxxm:previousReportAerodrome>` always the same?

`<iwxxm:previousReportAerodrome>` seems to be a superfluous element and just adds unnecessary complexity and bloat to the resulting XML document.

**Comment by blchoy** [comment]
In IWXXM METAR/SPECI, TAF, AIRMET and SIGMET has attribute "status" to indicate the kind of message they are (e.g. amendment, cancellation, etc).  Only TAF, AIRMET and SIGMET has elements making reference to previous messages.  There are no status attribute in the advisories.

Seems to me that we may need to align the need of references to previous messages.  Furthermore, the relationship between "issueTime" and "previous time" under different situations (e.g. correction, amendment, cancellation, etc.) should be listed out as there is only one date-time group in TAC and it takes different form under different situations.

**Comment by blchoy** [comment]
In the telecon on 24 Aug 2018, participants had no objection to remove "previousReportAerodrome".

**Comment by blchoy** [comment]
This is fixed in 3.0.0RC2.
