### ISSUE TITLE
IWXXM schema and TAC-to-XML-Guidance.txt conflict

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#107]
TAC-to-XML-Guidance.txt states:

> 'NIL' remarks
  NIL remarks shall be indicated with an missing "remarks" element

however, element `<iwxxm:remarks>` in VAA product is required

![vaa-remarks](https://user-images.githubusercontent.com/7852621/44181765-87b20500-a0d1-11e8-822a-e29fbc3641bf.PNG)

**Comment by blchoy** [comment]
Oh~ I am not the one who write this but when I read it I think it is not entirely wrong: When you "indicate" a remarking is nil you have to show something instead of removing it entirely, and the only way to do that is by saying `<iwxxm:remarks ... nilReason=".../missing"/>`.

But I may be thinking too much.  :)

**Comment by blchoy** [comment]
I share the same view with you.  So far the TAC-to-XML guidance document has been developed in a very simple way and I think we may want to start working on a more formal guidance document together with other materials mentioned in the tutorials on the WMO WIS Wiki.  My first question is whether this is going to be a numbered document under WMO or ICAO?  Perhaps @efucile could enlighten us in this respect?

**Comment by blchoy** [comment]
I changed the title to extend our discussion to also include #105 which is similar in nature.

**Comment by blchoy** [comment]
There are some improvements to the guidance and this issue is considered to have been fixed.

**Comment by petringo** [comment]
Hi all,

Although this issue has been closed over two years ago, I found that again there's a conflict between IWXXM schema and TAC to XML Guidance on nil remarks.

Documentation concerning nil remarks in all of [volcanicAshAdvisory.xsd](https://github.com/wmo-im/iwxxm/blame/4d13795fba912ff6fa4d348c5232462c81f5b672/IWXXM/volcanicAshAdvisory.xsd#L83), [tropicalCycloneAdvisory.xsd](https://github.com/wmo-im/iwxxm/blame/4d13795fba912ff6fa4d348c5232462c81f5b672/IWXXM/IWXXM/tropicalCycloneAdvisory.xsd#L56) and [spaceWxAdvisory.xsd](https://github.com/wmo-im/iwxxm/blame/4d13795fba912ff6fa4d348c5232462c81f5b672/IWXXM/spaceWxAdvisory.xsd#L55) state:

> When the remark is nil, it should be indicated by a missing remarks with a nil reason of 'inapplicable'

while TAC-to-XML-Guidance.txt states on [Volcanic Ash Advisory](https://github.com/wmo-im/iwxxm/blame/ef4c476e399cc5b01b5ab35174f43d2a8f00af03/IWXXM/examples/TAC-to-XML-Guidance.txt#L176), [Tropical Cyclone Advisory](https://github.com/wmo-im/iwxxm/blame/ef4c476e399cc5b01b5ab35174f43d2a8f00af03/IWXXM/examples/TAC-to-XML-Guidance.txt#L176) and [Space Weather Advisory](https://github.com/wmo-im/iwxxm/blame/ef4c476e399cc5b01b5ab35174f43d2a8f00af03/IWXXM/examples/TAC-to-XML-Guidance.txt#L212):

> NIL remarks shall be indicated with "remarks" nilReason set to "http://codes.wmo.int/common/nil/missing"

I would guess the schema documentation is probably what should be followed in implementation.

**Comment by mgoberfield** [comment]
Hi @petringo,

As @blchoy is busy, I will respond.

Thank you for pointing out the inconsistency. WMO No. 306 Manual on Codes is the authoritative source on such matters and not the TAC-to-XML Guidance, nor the schema documentation. 

The WMO No. 306 Manual on Codes and schema documentation agree and it is the TAC-to-XML Guidance text file that is in error.

All IWXXM 3.0 examples of NIL remarks in TAC on the IWXXM schema website are correctly encoded in XML with nilReason of [inapplicable](http://codes.wmo.int/common/nil/inapplicable).

I will submit a pull request to correct the error in the TAC-to-XML-Guidance text file.

Best regards,

mark

**Comment by petringo** [comment]
Thank you @mgoberfield for pointing out the WMO No. 306 Manual on Codes being the authoritative source, I had totally missed that. And thanks for supplying the fix to the TAC-to-XML-Guidance.

**Comment by blchoy** [comment]
Thank you.  The mistakes shall be fixed in IWXXM 3.1.
