### ISSUE TITLE
Create and/or release WMO Codes Registry scripts

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#11]
In TT-AvXML-4 it was determined that a set of scripts to download WMO Codes Registry entries and cache them locally was necessary to support operational use cases where live access to the WMO Codes Registry could not be assumed. Operational use is starting and this type of script is therefore quite important.

The following capabilities must be supported:

    Download a local copy of either the entire or a partial set of the WMO Codes Registry
    Update the local copy with the current "live" content
    Check whether a particular URL is currently valid (not deprecated) from the live site
    Check whether a particular URL is currently valid (not deprecated) based on local cache content

ref: https://software.ecmwf.int/issues/browse/AVXML-20

Created:
    29/Sep/15 9:24 PM 

Reporter:
Aaron Braeckel

**Comment by braeckel** [comment]
This was completed in IWXXM 2.1, and scripts are currently checked in.  This issue can be closed
