### ISSUE TITLE
Expressing bulletin headers (like RRA) in IWXXM Collections

### ISSUE THREAD

**Issue by ilkkarinne** [wmo-im/iwxxm#119]
Is there any guidance on encoding the bulletin headers within the collect:MeteorologicalBulletin in IWXXM? The practical case I'm trying to solve is how to encode late (RTD) METAR and TAF messages in IWXXM.

**Comment by blchoy** [comment]
Please provide feedback to or raise your question in Google group cbs-tt-avxml@wmo.int.

**Comment by ilkkarinne** [comment]
Ok, have done so
