### ISSUE TITLE
taf-A5-2.xml should not have a validTime

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#121]
TAF A5-2 cancels a previous TAF, but should not itself report a validTime.  The validTime should be removed, and the Schematron rules modified (if necessary) to allow this in cancellation cases.

**Comment by blchoy** [comment]
We will have to detour to another issue #125 to fix another problem before coming back.

**Comment by blchoy** [comment]
This has been incorporated in 3.0.0RC2.  Interesting to note that SIGMET and AIRMET still have validPeriod in their cancellation messages.
