### ISSUE TITLE
Consistency of element naming and ordering across different types of reports

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#127]
The current advisories all have a "next advisory time" element.

TCA is the outlier with a 'expectedNextAdvisoryTime' element.  The VAA and SpaceWx advisories have 'nextAdvisoryTime' element.

TCA schema uses different names for maximum wind speeds in the observed and forecast portions of the document. Changed the forecast one to be consistent.  As a consequence the schematron rule was updated also.

 Commit f09043a2d656e5fc1a0167b35e09d419f25fe732 and 8491cb0b2d77923bcd5c5b002819e4a57fd40769  fix these inconsistencies.

**Comment by blchoy** [comment]
I have include the following changes in 3.0.0RC2:

TCA: expectedNextAdvisoryTime -> nextAdvisoryTime
TAF: previousReportValidPeriod now located immediately after validTime
SIGMET: volcanicAshMovedToFIR now moved from SIGMET to VolcanicAshSIGMET

For VAA, it seems to me that a single 'analysis' with type 'VolcanicAshConditions' may not be able to cover both OBS/FCST and FCST description blocks (c.f. SWA where the format of both OBS/FCST and FCST sections are almost the same).  Further work will have to be done for VAA.

**Comment by mgoberfield** [comment]
To @blchoy, and et. al., how about the following changes to VAA model?
![vaa-1](https://user-images.githubusercontent.com/7852621/47096793-f27cdb00-d1fd-11e8-8aaa-6768f0c07ddb.PNG)
This change makes observed and forecast portions of the advisory explicit, so as to be consistent with other IWXXM schemas (based on IWXXM_element document).
![vaa-2](https://user-images.githubusercontent.com/7852621/47099881-3f63b000-d204-11e8-95ea-2ac058306daa.PNG)

The boolean 'estimated' is needed since Annex 3 allows for estimated (EST) DTG and VA cloud position. Otherwise, it could be set to 'false' or not set at all when VA cloud(s) is/are explicitly observed (and so indicated in the TAC.)
![vaa-3](https://user-images.githubusercontent.com/7852621/47099128-9e282a00-d202-11e8-9625-5c7a590b496b.PNG)

For the changes to VolcanicAshCloud featureType, the 'windLower(Upper)Limit(Reference) were removed (as decided/recommended in #100). In the case of VA NOT IDENTIFIABLE, a layer is mandatory. This information is now contained in the AirspaceVolume element.

![vaa-4](https://user-images.githubusercontent.com/7852621/47099379-29092480-d203-11e8-857f-1846fc04f64d.PNG)

So, in this case of "VA NOT IDENTIFIABLE", the new attribute 'notDirectlyObserved' shall be set to 'true', otherwise not used (or set to 'false'). The existing guidance for VAA cases in the TAC-to-XML-Guidance document can still be applied with appropriate changes as shown here.

'VA NOT IDENTIFIABLE FM SATELLITE DATA'
  Unidentifiable volcanic ash from satellite data shall be indicated with attribute notDirectlyObserved set to 'true'.
  
'NO VA EXP'
  When no volcanic ash is expected it shall be indicated with a "ashCloudExtent" with a nilReason of "http://codes.wmo.int/common/nil/nothingOfOperationalSignificance"
  
'NOT AVBL'
  When volcanic ash is not available it shall be indicated with a "ashCloudExtent" with a nilReason of "http://codes.wmo.int/common/nil/missing"

'NOT PROVIDED'
  When volcanic ash is not provided it shall be indicated with a "ashCloudExtent" with a nilReason of "http://codes.wmo.int/common/nil/withheld"

For your consideration.

**Comment by blchoy** [comment]
Oh @mgoberfield I just edited my previous post to indicate I have accomplished my modifications without noticing that you have put some questions after it.  What I have done can be summarized in the following diagrams which I will try to explain tomorrow during the telecon:

**Comment by mgoberfield** [comment]
@blchoy, my thoughts on your revised VAA model:

Need to indicate variable wind in the WindObservedOrEstimated featureType, so windDirection cardinality needs to be [0..1] and a boolean attribute 'variableWindDirection' to signify that.

For VolcanicAshForecastConditions featureType, what shall forecastStatus value be when ash clouds **are** observed?  I would re-think the relationship between forecastStatus and ashCloud elements.

Also the cardinality of ashCloud elements should be [1..* ] for observed and [0..* ] for forecast components of the model. More than one ash cloud can be given in the analysis and forecast periods. See FVAU03ADRM-0424.xml for a real-world example in the VAA iwxxm-translation repository.

 With your proposed model changes, I see no reason to supply an ashCloud element if forecastStatus is "NO VA EXP", "NOT AVBL" or "NOT PROVIDED" hence my suggest to make ashCloud element optional for the forecasts.

V/R,

mark

**Comment by blchoy** [comment]
Thank you for your prompt reply Mark.  I have include all your suggestions and the revised class diagrams are as follow:

![context diagram volcanic ash observed conditions](https://user-images.githubusercontent.com/30064374/47136482-5da1dc80-d2e6-11e8-80fc-103c04c5e00b.png)
![context diagram volcanic ash forecast conditions](https://user-images.githubusercontent.com/30064374/47136484-609ccd00-d2e6-11e8-924d-b93b31d46474.png)

**Comment by mgoberfield** [comment]
Hello Choy,

Both elements that use the enumerations you've defined above are required. Yet all entries of the enumerations are in the "negative" sense. I would add one positive entry for each. So for VolcanicAshObservableOrEstimatedStatus enumerated type, the entries would be "Identifiable" and "Not Identifiable". (Or consider changing this element and use a boolean attribute to convey this condition instead)

For VACloudForecastStatus (please consider changing to VolcanicAshCloudForecastStatus for consistency), the enumerated entries would be "Provided", "No Volcanic Ash Expected", "Not Available", "Not Provided".

I don't know if there's an established XML convention about whether the enumerations entries should be in upper-case letters or not.

For your consideration,

mark

**Comment by blchoy** [comment]
> And VolcanicAshCloudForecast featureType needs directionOfMotion and speedOfMotion elements.

I am not too sure about this:

![image](https://user-images.githubusercontent.com/30064374/47158800-fe13f300-d31e-11e8-99bd-903250fd32ee.png)

**Comment by mgoberfield** [comment]
Yes. You're right.  Need caffeine...

mark

**Comment by blchoy** [comment]
@mgoberfield, I have revised the model (mostly) in accordance to your further suggestions:

![context diagram volcanic ash observed conditions](https://user-images.githubusercontent.com/30064374/47194480-12d9a080-d38a-11e8-8b82-c949f2ce4671.png)
![context diagram volcanic ash forecast conditions](https://user-images.githubusercontent.com/30064374/47194484-179e5480-d38a-11e8-91e5-8ceea3775b09.png)

> Or consider changing this element (i.e. IDENTIFIABLE/NOT_IDENTIFIABLE) and use a boolean attribute to convey this condition instead

While this is binary right now, I don't know when it will become non-binary so my best bet is to keep this arrangement which also aligns with the forecast part.

> I don't know if there's an established XML convention about whether the enumerations entries should be in upper-case letters or not.

Currently it is all caps with underscores in place of white spaces in between words in other reports so I suggest we continue this practice.

**Comment by blchoy** [comment]
This has been incorporated into 3.0.0RC2.
