### ISSUE TITLE
SIGMET OBS AT nnnnZ ENTIRE FIR

### ISSUE THREAD

**Issue by infidel** [wmo-im/iwxxm#129]
In a volcanic ash SIGMET, the schema comments say that ENTIRE FIR should be represented such that "the geometry should be an xlink to the sampled feature for this SIGMET". However, <iwxxm:geometry> doesn't allow an xref:hlink attribute. In the forecast I can see a possibility:

<iwxxm:forecastPositionAnalysis>
    <om:OM_Observation gml:id="va-forecast-position-EGGX-YYYYMM25T22Z">
...
        <om:result>
            <iwxxm:SIGMETPositionCollection gml:id="mpc-EGGX-YYYYMM25T16Z">
                <iwxxm:member xlink:href="#ss-SHANWICK_OCA"/>
            </iwxxm:SIGMETPositionCollection>
        </om:result>
    </om:OM_Observation>
</iwxxm:forecastPositionAnalysis>

This validates but is it correct? However, in the <SIGMETEvolvingConditionCollection> I don't see how to do anything similar because the <iwxxm:member> also wraps the Level elements which still need to be included. How can we encode OBS AT 1210Z ENTIRE FIR?

An example TAC from EUR Doc 014:

> YUDD SIGMET 2 VALID 101200/101600 YUSO –
YUDD SHANLON FIR/UIR VA CLD FCST AT 1200Z ENTIRE FIR FL250/370 STNR WKN=

I'm posting here because I didn't get any replies on the group: https://groups.google.com/a/wmo.int/d/msg/cbs-tt-avxml/udbYFyTiza4/2_7W2mEfCAAJ

**Comment by blchoy** [comment]
I have to say that iwxxm:geometry in SIGMET was designed to have xlink:href but due to some mistakes it was incorrectly defined in the schema as:

`<element name="geometry" type="aixm:AirspaceVolumePropertyType"> `

which should instead be:

`<element name="geometry" type="iwxxm:AirspaceVolumePropertyType">`

We fixed this in IWXXM 3.0.0.  In this version, the FIR/UIR/CTA is defined to be:

```
    <iwxxm:issuingAirTrafficServicesRegion>
        <aixm:Airspace gml:id="uuid.eb9d349c-242c-4193-981a-935ee2e547a2">
            <aixm:timeSlice>
                <aixm:AirspaceTimeSlice gml:id="uuid.23909d58-4be9-43a1-8eb8-2d1e3b64432e">
                    <gml:validTime/>
                    <aixm:interpretation>SNAPSHOT</aixm:interpretation>
                    <aixm:type>OTHER:FIR_UIR</aixm:type>
                    <aixm:designator>YUDD</aixm:designator>
                    <aixm:name>SHANLON FIR/UIR</aixm:name>
                    <!-- FIR boundary can be reported in an aixm:geometryComponent -->
                </aixm:AirspaceTimeSlice>
            </aixm:timeSlice>
        </aixm:Airspace>
    </iwxxm:issuingAirTrafficServicesRegion>
```

where the FIR/UIR/CTA boundary is defined as:

```
                    <aixm:geometryComponent>
                        <aixm:AirspaceGeometryComponent gml:id="...">
                            <aixm:theAirspaceVolume>
                                <aixm:AirspaceVolume gml:id="uuid.eb9d349c-242c-4193-981a-935ee2e547a2">
                                    ...
                                </aixm:AirspaceVolume>
                            </aixm:theAirspaceVolume>
                        </aixm:AirspaceGeometryComponent>
                    </aixm:geometryComponent>

```

You can then make reference by:

        `<iwxxm:geometry xlink:href="#uuid.eb9d349c-242c-4193-981a-935ee2e547a2"/>`
