### ISSUE TITLE
VAA schema should allow for multiple flight level layers for wind data

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#131]
There is no explicit restriction in Annex 3 for reporting more than one flight level layer wind data point  in VA NOT IDENTIFIED case.

Propose that maxOccurs be changed from '1' to 'unbounded' on the following line:
https://github.com/wmo-im/iwxxm/blob/b5ec9badedcad221d2e4b63c6ed3f659e1b8b4d3/3.0.0RC2/volcanicAshAdvisory.xsd#L108

**Comment by blchoy** [comment]
Agreed with changes merged in commit https://github.com/wmo-im/iwxxm/pull/134/commits/40b2098ac6a27a75ef9a2df94898b2cc27b79044.
