### ISSUE TITLE
METAR_SPECI rule suspect

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#132]
Rule

https://github.com/wmo-im/iwxxm/blob/b5ec9badedcad221d2e4b63c6ed3f659e1b8b4d3/3.0.0RC2/rule/iwxxm.sch#L23

may be incorrect.  The case of runway(s) cleared of contaminates and friction coefficient or braking action provided should be allowed.

As encoded in TAC form:  "R88/CLRD70"

condition "and empty(iwxxm:estimatedSurfaceFrictionOrBrakingAction)" should be removed to fix.

**Comment by blchoy** [comment]
Agreed with changes merged in commit https://github.com/wmo-im/iwxxm/pull/134/commits/40b2098ac6a27a75ef9a2df94898b2cc27b79044.
