### ISSUE TITLE
306 v3 Changes Review

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#143]
Review Proposed changes to WMO 306 for IWXXM 3.0.0

**Comment by marqh** [comment]
Initial version for review is at http://wiswiki.wmo.int/tiki-download_file.php?fileId=5179

**Comment by blchoy** [comment]
Make sure that there are words mandating srsDimension=2, and compatible with the value in srsName.

**Comment by marqh** [comment]
I have completed a set of edits to the document previously posted on this ticket.

In summary:
* all URIs are properly represented, as underlined text, with linkage, and no space characters inserted into text
* all requirement identification URIs use http://def.wmo.int/iwxxm/3.0/req as a prefix (replacing the unresolvable http://icao.int/iwxxm structure)
* space characters removed from all XML snippets 
* table and section numbering now consistent
* new section 205-XX.55 Requirements class: SIGMET to avoid conditional dependencies and requirements
 * 205-XX.26 Requirements class: SIGMET core replaces legacy SIGMET section, with only shared information for SIGMET, SIGMET Tropical Storm and SIGMET Volcanic

There remains an outstanding activity, required to ensure that CRS limitations are proscribed, mandating srsname usage, srsDimension=2 usage, as previously commented


This document is ready for review

[IWXXM3.0Attachment.docx](https://github.com/wmo-im/iwxxm/files/3048450/IWXXM3.0Attachment.docx)

**Comment by marqh** [comment]
@efucile @mgoberfield @dzinkhan @jkorosi @blchoy 
notification

**Comment by jkorosi** [comment]
I have following questions:

1. Shouldn't be 7 point rules avoided in IWXXM?
2. Should be somewhere mention that gml:id in IWXXM should be UUID4?
3. I think that http://def.wmo.int/iwxxm/3.0/req/xsd-sigmet-core/is-cancel-report requirement implies 
the reportStatus equal to AMENDMENT.
4. The RTD reports are not handled. Should it be present in this document?

**Comment by marqh** [comment]
following TT AvXML meeting, on 10th April 2019, items 1&2 from https://github.com/wmo-im/iwxxm/issues/143#issuecomment-481662832 are accepted and items 3&4 are not accepted as additions.

**Comment by marqh** [comment]
I have updated the document to include the UUID definition as a new requirement class and to include the CRS elements as a new requirement class

I do not consider this complete, as the dependencies of other requirement classes on these two new classes have not been fully defined.  This needs completing.

I present this version for ongoing review

[IWXXM3.0Attachment.docx](https://github.com/wmo-im/iwxxm/files/3086141/IWXXM3.0Attachment.docx)

**Comment by blchoy** [comment]
Thanks @marqh for preparing the updated draft.  I think we need to discuss:

1. Currently the requirement classes included under IWXXM-XML are basically the XML elements defined in the schemas.  The new CRS and gml:id requirement classes are schematron rules.  They are different types of requirements and I do think both of them should be included.

2. The CRS and gml:id requirements can be specify at element level, but in the gml:id case there could be a lot.  Do we want to be specific or a covering description is enough?

**Comment by marqh** [comment]
I have completed my updates to the 306 proposal document.

This now includes:
* dependency references between CRS and position classes 
 * as best as I can; review very much welcomed
* UUID mandate
 * dependency referencing not provided
* extension capability mandate
* removal of seven point rule recommendation 

[IWXXM3.0Attachment.docx](https://github.com/wmo-im/iwxxm/files/3090669/IWXXM3.0Attachment.docx)


@efucile please may you validate whether this older format is able to be opened by legacy technologies, as you requested?

**Comment by blchoy** [comment]
My suggested updates which include:

- references to requirements classes crs, uuid and extension were added to requirement classes/elements involved
- changes relating to the VA Advisory deficiencies mentioned in #153 were included (Note that I have changed a little bit of the proposed representation of the new elements.  Please check the post and report back if there is an issue)
- correction to typos

The file is here: [IWXXM3.0Attachment-choy.docx](https://github.com/wmo-im/iwxxm/files/3102864/IWXXM3.0Attachment-choy.docx)

@marqh and @efucile: Please see if the proposed addition meets your expectation.

**Comment by mgoberfield** [comment]
Dear Choy (@blchoy ), Mark (@marqh), et. al.

Is AIXM information in Table 205-XX.2.2 correct? Our CI software refers to a specific profile of AIXM (see the catalog.template file).

**Comment by blchoy** [comment]
Thanks for pointing out Mark.  You are right, while a schemaLocation of http://www.aixm.aero/schema/5.1.1/AIXM_Features.xsd is not wrong, we are promoting the use of the AIXM Weather Profile at http://aixm.aero/schema/5.1.1_profiles/AIXM_WX/5.1.1b/AIXM_Features.xsd to use a reduced version of the schema.  You also reminds me that I will also need to change the schemaLocation in common.xsd too.

**Comment by efucile** [comment]
Here is the version that I am using for formal approval
[FM205-2018-IWXXM3.0.docx](https://github.com/wmo-im/iwxxm/files/3106844/FM205-2018-IWXXM3.0.docx)

**Comment by efucile** [comment]
@marqh this is a doc version of Vol. I.3 
[306_I3_en.docx](https://github.com/wmo-im/iwxxm/files/3111644/306_I3_en.docx) 
however I have to make the changes as we use a special way to indicate changes in the manuals that is in our word tools. Just cut the page that you want to change and make the changes with track changes on.

**Comment by marqh** [comment]
@efucile 
many thanks for the document

I have made a set of tracked changes updates to appendices A and B:
* Appendix A
  * Restructured Code Table D-1 in document
    * to improve clarity
  * Altered some URIs such that all URIs in the code table are defined within http://codes.wmo.int/common/nil
    * for consistency and clarity 
    * removed text explaining that some terms are defined within opengis.net, as the proposal is that this no longer applies
* Appendix B Section 5
  * Removed references to IWXXM 1.1:
    * this change is dependent on whether IWXXM 1.1 is removed from the main body of the document
  * Added new sub-section detailing schema locations for IWXXM 3.0

[appendix_updates_306_I3_en.docx](https://github.com/wmo-im/iwxxm/files/3120910/appendix_updates_306_I3_en.docx)


I hope this document change is clear and importable for you

**Comment by blchoy** [comment]
@efucile : The following is a last minute change to Vol. I.3 in track-change mode before your submission:
[FM205-2018-IWXXM3.0-choy.docx](https://github.com/wmo-im/iwxxm/files/3124121/FM205-2018-IWXXM3.0-choy.docx)

**Comment by efucile** [comment]
@blchoy and @marqh do we have a simple list of the most significant changes that I can include in the communication to the focal points for the official consultation?

**Comment by blchoy** [comment]
I suggest:
1. Add Amendment 78 to ICAO Annex 3/WMO No.49 II changes, including
   * Introduction of the Space Weather Advisory
   * Changes involving the Tropical Cyclone Advisory
2. Mandate the use of
   * 2 dimensional coordinate reference systems for spatial referencing
   * UUID identifier in gml:id
3. Simplify representation by removing the OGC Observation and Measurement construct
4. Fixed bugs and deficiencies in representations of various reports

**Comment by efucile** [comment]
Document to be sent to national focal points for consultation is here 
[FT2019-2 WMO-306 Vol I.3.docx](https://github.com/wmo-im/iwxxm/files/3138349/FT2019-2.WMO-306.Vol.I.3.docx) @marqh and @blchoy please have a quick look

**Comment by blchoy** [comment]
@efucile : I thought it should be FM205-2019 instead of 2018?

**Comment by blchoy** [comment]
As the draft document has been submitted for approval, this thread can be closed.
