### ISSUE TITLE
nil_reason 

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#155]
http://codes.wmo.int/common/nil

includes a number of register items where the entity is an OGC reference, including
http://codes.wmo.int/common/nil/_withheld
http://codes.wmo.int/common/nil/_unknown
http://codes.wmo.int/common/nil/_missing

so 
http://codes.wmo.int/common/nil/withheld
http://codes.wmo.int/common/nil/unknown
http://codes.wmo.int/common/nil/missing
do not resolve

question Update to code table D! to include these as full WMO URIs??

**Comment by marqh** [comment]
see #97

**Comment by blchoy** [comment]
Once fixed, we need also to follow up on:

1. Scripts to download RDF should include http://codes.wmo.int/common/nil
2. To re-introduce relevant checking rules in iwxxm.sch which is absent right now because of the broken RDF file mentioned in #97

**Comment by blchoy** [comment]
This was fixed in 3.0.0RC4.
