### ISSUE TITLE
Make all observed fields optional with a nilReason (such as METAR)

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#16]
ICAO is not directing us to do this.

ref: https://software.ecmwf.int/issues/browse/AVXML-40

    Reporter:
        Aaron Braeckel 

    Created:
        20/Nov/15 4:31 PM

**Comment by marqh** [comment]
B L Choy added a comment - 22/Nov/15 5:32 PM - edited

I am not sure if the title should read "Make all observed fields nillable with a nilReason (such as METAR)"?

Yet in Para. 15.4 of WMO No. 306 Manual on Codes Vol I.1, it was mentioned that solidi can be used in METAR/SPECI groups if the elements they represent cannot be observed in automated observations without human intervention.

I think making all observed fields nillable and control allowable combination of properties for "nil" with schematron rules (e.g. for wind the only allowable case for "nil" is AUTO and a nilReason of "http://codes.wmo.int/nilReason/SensorFailed") is a more flexible way to implement validation with permissible failure in certain elements.

**Comment by braeckel** [comment]
This is a duplicate with #23 and will be closed
