### ISSUE TITLE
Missing temperatures

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#165]
During testing and validation of IWXXM v3.0 TAFs, a common validation error occurs when only one temperature extrema is provided in the TAF.  For example, max temperature and time of occurrence is provided, but not minimum temperature/time -- it's missing entirely (no use of solidus).  The missing temperature element cannot be nil'ed. 

Should the TAF be considered invalid in such cases or iwxxm:min(max)imumAirTemperature element type be changed to be nillable?

**Comment by blchoy** [comment]
Currently the temperature forecast block is optional, but when present it must contain a maximum AND a minimum temperature forecast.  This is our interpretation of the 'O's and 'M's in the Annex 3 template.  We checked the data in 2017 and noticed that only one aerodrome reported a single max or min, but there are a lot reporting 2 max + 1 min or 1 max + 2 min.  The latter suggests that the majority of the cases consist of typical bell (or inverted bell) shaped profile.  To straightly comply with Annex 3 we may want to repeat the single peak or trough value but obviously this is not the case for TAC.

I agree with you that we may want to take this last opportunity to make the max and min nillable, or even optional to align with existing not so Annex 3 compliant practice.  If there is any discussion telling us that the former interpretation is indeed the correct way to do things that should surely give us more confidence to make the change!

**Comment by blchoy** [comment]
Tim Hailes had give us his opinion on this matter:

> I believe there are 3 things that each indicate that temperatures should be provided in pairs of maximum and minimum. These being:
> 
> 1. Table A5-1 – The "temperature" (group) element is optional, not the individual temperature forecast fields;
> 2. The temperature examples always show pairs of temperature forecasts. If single temperatures were allowed then these should be included in the examples; and
> 3. Appendix 5 section 1.2.5 states the maximum and minimum. It doesn't say maximum and/or minimum or similar.
>
> 1.2.5 Temperature
> 
> **Recommendation**.— _When forecast temperatures are included in accordance with regional air navigation agreement, the maximum and minimum temperatures expected to occur during the period of validity of the TAF should be given, together with their corresponding times of occurrence._

So it is not a representation issue but coding issue, which applies to both TAC and IWXXM.  It is also a potential problem for TAC-to-IWXXM translation: shall we treat odd numbers of TX/TN in TAC untranslatable and make partially translated IWXXM counterparts?

**Comment by blchoy** [comment]
I am closing this at the moment as there is nothing to be done from TT-AvXML perspective until the relevant requirements in Annex 3 has changed.
