### ISSUE TITLE
ICAO TCA issues

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#166]
Recent TCAs indicate that current technical specifications do not handle the situation well.

Please consider
```
FKPQ30 RJTD 270000
TC ADVISORY
DTG:                 20190727/0000Z
TCAC:                TOKYO
TC:                  NARI
NR:                  13
PSN:                 N3440 E13625
MOV:                 NNE 12KT
C:                   1000HPA
MAX WIND:            35KT
FCST PSN +6HR:       27/0600Z N3520 E13720
FCST MAX WIND +6HR:  NIL
FCST PSN +12HR:      27/1200Z N3550 E13820 TROPICAL DEPRESSION
FCST MAX WIND +12HR: NIL
FCST PSN +18HR:      27/1800Z N3625 E13940 TROPICAL DEPRESSION
FCST MAX WIND +18HR: NIL
FCST PSN +24HR:      28/0000Z N3700 E14110 TROPICAL DEPRESSION
FCST MAX WIND +24HR: NIL
RMK:                 NIL
NXT MSG:             20190727/0600Z =
```
While forecast positions are provided, maximum wind speeds are not.  The technical specs do not allow maximumWindSpeed element to be nill'd (or indicate speeds below a certain threshold/criterion).

Another case:
```
FKNT23 KNHC 231458
TCANT3
 
REMNANTS OF THREE ICAO ADVISORY NUMBER   4
NWS NATIONAL HURRICANE CENTER MIAMI FL       AL032019
1500 UTC TUE JUL 23 2019
 
TC ADVISORY
DTG:                      20190723/1500Z
TCAC:                     KNHC
TC:                       THREE
NR:                       004
PSN:                      N2900 W08000
MOV:                      N 15KT
C:                        1014HPA
MAX WIND:                 030KT
FCST PSN +6 HR:           23/2100Z N//// W/////
FCST MAX WIND +6 HR:      ///KT
FCST PSN +12 HR:          24/0300Z N//// W/////
FCST MAX WIND +12 HR:     ///KT
FCST PSN +18 HR:          24/0900Z N//// W/////
FCST MAX WIND +18 HR:     ///KT
FCST PSN +24 HR:          24/1500Z N//// W/////
FCST MAX WIND +24 HR:     ///KT
RMK:                      THE FORECAST POSITION INFORMATION IN
                          THIS PRODUCT IS INTERPOLATED FROM
                          OFFICIAL FORECAST DATA VALID AT 0000...
                          0600...1200...AND 1800Z.
NXT MSG:                  NO MSG EXP
```
In this case, the tropical depression dissipates entirely within 6 hours--sheared and absorbed into a frontal system--and no forecast positions or wind information can be provided.

The current specifications for TCAs seem not to take into account TC dissipation well and TCACs have been creative in trying to account for them given the current format.

Knowing it's late, but making maximumWindSpeed (and forecast positions?) nillable considered a  bug fix to v3.0?  (ie. 3.0RC4).  Better handling of TC dissipation may be considered for v3.1?

Respectfully submitted.

**Comment by blchoy** [comment]
@mgoberfield you are right.  As the forecast groups and the elements they contain are mandatory, the only way to represent a forecast TC which has an uncertain location because it is either too week to be identified or has transitioned into an extra-tropical low, or intensity has dropped below warning requirement, is to make them nil with nilReasons.

![image](https://user-images.githubusercontent.com/30064374/62146278-a41d7080-b327-11e9-82b2-f2f3aa9df0ac.png)

**Comment by blchoy** [comment]
Checking tropicalCyclonePosition and maximumSurfaceWindSpeed can be made nillable with nilReasons.  Will do in IWXXM 3.1.

**Comment by mgoberfield** [comment]
I do like  http://codes.wmo.int/common/nil/nothingOfOperationalSignificance when wind speed value isn't provided.  IMO, it's a 'toss-up' between http://codes.wmo.int/common/nil/inapplicable and http://codes.wmo.int/common/nil/missing when TC position is not provided.

**Comment by blchoy** [comment]
> IMO, it's a 'toss-up' between http://codes.wmo.int/common/nil/inapplicable and http://codes.wmo.int/common/nil/missing when TC position is not provided.

My order of preference:
1. inapplicable - I have full understanding of the situation and I know it does not fit into the reporting criteria
2. missing - I may or may not know the situation and I choose not to tell you anything
3. unknown - I know I don't know... probably too honest  :)

By the way, I will put in "nothingOfOperationalSignificance" and "inapplicable" in the TAC-to-XML-Guidance.txt first and wait for comments.

**Comment by mgoberfield** [comment]
From the code registry

1.  Missing - The correct value is not readily available to the sender of this data. Furthermore, a correct value may not exist.
2. Inapplicable - There is no value.
3. Unknown - The correct value is not known to, and not computable by, the sender of this data. However, a correct value probably exists.

I do agree that unknown is the last.

**Comment by mgoberfield** [comment]
Happy to see that you turned on the Discussion feature.

**Comment by blchoy** [comment]
> Happy to see that you turned on the Discussion feature.

I didn't.  It must be @amilan17.  She IS the administrator we are long looking for.  :)

**Comment by blchoy** [comment]
This was fixed in IWXXM 2021-2RC1.
