### ISSUE TITLE
XSD - Missing 	<include schemaLocation="measures.xsd"></include>

### ISSUE THREAD

**Issue by dearith** [wmo-im/iwxxm#167]
Hi, 
In the xsd documents (e.g. sigmet.xsd), the 

	`<include schemaLocation="measures.xsd"></include>`

is missing and the xsd files are detected as not valid by XML validators tools 

(e.g.

**Comment by mgoberfield** [comment]
At the moment we intend users to refer to the top-level schema file, iwxxm.xsd, and not the individual "sub-packages". We may remove this constraint shortly.
