### ISSUE TITLE
Guidance on STNR is inconsistent

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#169]
From Annex 3
![stnry](https://user-images.githubusercontent.com/7852621/64716325-2e610480-d490-11e9-90e8-a0148a092443.png)

Currently, AIRMET/SIGMET direction is nillable.  Direction and speed are both optional. However, this is inconsistent with how stationary Tropical Cyclones are represented in TCA
![tc](https://user-images.githubusercontent.com/7852621/64717485-6d905500-d492-11e9-8fd6-a1333a96c4f7.png)

**Comment by blchoy** [comment]
I agree that making directionOfMotion nil and speedOfMotion zero for STNR in airmet-A6-1a-TS.xml is not as intuitive as leaving them out as the latter is also what the TAC template in Annex 3 is telling.  So we may want to put a few words in the guidance and also amend the example.

**Comment by mgoberfield** [comment]
Please see #187
