### ISSUE TITLE
Inclusion of TAC in examples

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#170]
We have received numerous communications about the relationship between TAC and IWXXM encodings and the presence of TAC encodings in 'comments' in the IWXXM encoding.

Indeed some communications suggested inclusion of TAC as an element within the IWXXM. Other comments referred to extracting the comment and using it directly.

Given the aims of ICAO MetPanel and WMO to retire TAC in 2026, the aim targeted by the task team is to provide IWXXM as a replacement.

On this basis, I propose removing the TAC example comments from all of the examples prior to publishing as IWXXM 3.0.0
This is a change, but it is a non-functional change, not changing the actual XML in the examples.

I think that this is appropriate and sensible step to take, to reduce the likelihood that  real messages include TAC in a comment, or even worse, include wrong TAC, as a result of following examples published by WMO.

**Comment by blchoy** [comment]
> I think that this is appropriate and sensible step to take, to reduce the likelihood that real messages include TAC in a comment, or even worse, include wrong TAC, as a result of following examples published by WMO.

Recalling that when I install a software I will also use the sample configuration file to start off leaving unused directives as comments in it which is dangerous if accidentally changed I fully support this action.

**Comment by blchoy** [comment]
This was implemented in 3.0.0RC4.
