### ISSUE TITLE
UUID Identifier

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#172]
GML:ID UUID

Use and Implications

There is a documentation requirement, targeted at providers and producers of IWXXM, providing information on the use and creation of UUID instances

In particular, this should provide information on the implications of an ID on an element.  How does reuse of elements, changing of messages, reformatting, and other suchc factors, impact on the UUID implementation

Future work: for context: UUID as a referenceable Identifier.  Identifying elements in one message from another message

**Comment by blchoy** [comment]
There is [a white paper from Solitec](http://adq-suite.aero/documents/WhitePaper_UUID_Registry.pdf) proposing the setting up of a UUID Registry to support the identification of an AIXM feature.

While having a registry of MET feature is probably to far fetched, may be @porosnie could shed some lights on what is happening with regard to using UUID in gml:id as a permanent identifier of an AIXM feature?

**Comment by porosnie** [comment]
The AIXM rules for UUID are documented here: http://aixm.aero/sites/aixm.aero/files/imce/AIXM51/aixm_feature_identification_and_reference-1.0.pdf 
Please note that UUID are used mainly for the gml:identifier (which is the persistent 'feature identifier' in AIXM. The gml:ID values are not persistent in AIXM, although it is possible to also use UUID (prefixed by 'uuid_" to ensure that they start with a letter (as a UUID could also start with a number, which is invalid for a gml:ID.

**Comment by blchoy** [comment]
Thanks @porosnie.  Seems to me that the AIXM features identified by gml:identifier may have a much longer life cycle than a weather feature which, for a 2.5D space enclosing a thunderstorm, could last for only a few hours.  Furthermore, the same feature when described in different messages may have more than one gml:identifier.

Having said that, I still think there are values to label a weather feature, in particular we may want to make reference to it in within a message or subsequent messages (e.g. correction, amendment, anticipated changes, etc.).  Will need to develop and examine related use cases.

**Comment by blchoy** [comment]
gml:identifier is being used to identify a WxObject or its collection.  At the moment it is not constrained to be a UUID as this requires consensus from the community on the necessity and if so how to uniquely identify these objects.  While this is work under development, I think the essence has been included in the implementation of WxObject in IWXXM 2021-2RC1 and this issue is hereby closed.
