### ISSUE TITLE
Compatability Table

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#174]
Write a compatability table

target: 306 I.3

first iteration : 3.0 | amendment 78

requirement
have different and multiple compatability for different message types

which way round is the content?

**Comment by marqh** [comment]
1. Option: Table in manual on codes, 
1. Option: For each IWXXM version, we state which IWXXM versions are mandatory for message types

**Comment by marqh** [comment]
Example:
IWXXM 3.0
* IWXXM 3.0 shall be used for METAR from <I-3.0-METAR-Date>
* IWXXM 3.0 shall be used for TAF  from <I-3.0-TAF-Date>

New release:

IWXXM 3.1
* IWXXM 3.1 should be used for METAR from <I-3.1-METAR-Date>
 * IWXXM 3.0 or later shall be used for METAR from <I-3.0-METAR-Date>
* IWXXM 3.1 shall be used for TAF  from <I-3.1-TAFDate>
 * IWXXM 3.0 and earlier versions shall not be used after <I-3.1-TAFDate>



* IWXXM<v> <shall|should|may|shall not> be used for <message-type> from <date>

**Comment by blchoy** [comment]
This discussion has been superseded by the decision to adopt a new IWXXM schema and code table versioning policy discussed [here](https://github.com/wmo-im/iwxxm/wiki/New-proposal-on-IWXXM-versioning) which on the IWXXM code list part followed in https://github.com/wmo-im/iwxxm-codelists/issues/11.  For completeness, the following table will be used to indicate version(s) of IWXXM meeting the requirements in Annex 3:

IWXXM Version|Compliance|Reason for Release|METAR/SPECI|TAF|SIGMET|AIRMET|Tropical Cyclone Advisory|Volcanic Ash Advisory|Space Weather Advisory|WAFS SIGWX Forecast|IWXXM Code Table
:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:
2032-2|Amendment 84|New Requirement|3.1|3.1|4.1|4.1|4.0|4.0|3.0|1.0|2032-2
2033-1|Amendment 84|Urgent bug fix|3.1|3.1|4.2|4.2|4.0|4.0|3.0|1.0|2032-2
2033-2|Amendment 84|Urgent Code Table fix|3.1|3.1|4.2|4.2|4.0|4.0|3.0|1.0|2033-2

**Comment by blchoy** [comment]
[One page](https://github.com/wmo-im/iwxxm/wiki/Package-Compatibility) has been created on GitHub wiki.  We will also need one for MoC.

**Comment by blchoy** [comment]
This is done with the preparation of the draft MoC for IWXXM 2021-2.
