### ISSUE TITLE
Code Registry Mistakes

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#175]
http://codes.wmo.int/49-2/CloudAmountReportedAtAerodrome
and
http://codes.wmo.int/49-2/SigConvectiveCloudType

are mis-direction registers, pointing to BUFR code tables, but losing the notation from the 49-2 publication

This must be re-implemented on the registry

examples including elements from the redirected bufr tables shall be removed from examples:
examples/taf-A5-1.xml
examples/speci-A3-2.xml
examples/metar-A3-1.xml

**Comment by mgoberfield** [comment]
A similar issue affects many of the common/nil registry entries.

**Comment by blchoy** [comment]
> 
> 
> A similar issue affects many of the common/nil registry entries.

True.  This was recorded in #155.

**Comment by blchoy** [comment]
This was fixed in 3.0.0RC4.
