### ISSUE TITLE
Visualisation Requirement

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#177]
Produce a paper for MIE

TT AvXML are escalating the challenge that requirements and standardisation for visualistion of IWXXM is not well defined.

The definition of these requires ownership, MRI is proposed as the owning group

Include:
  * paper from HMEI

Decision 5/01 of MetP/4 - Met Information Visualisation/Representation

**Comment by blchoy** [comment]
I suggest to merge this paper with mine on high fidelity data in IWXXM which is based on the assumption of the need of certain data in addition to existing METAR/SPECI.  I will take a case in Jan's paper and make an example on what IWXXM can do to elaborate the importance of end users' need in designing the data format (no longer the other way round).

**Comment by efucile** [comment]
@blchoy did you do this merge? Do we need this paper?

**Comment by efucile** [comment]
thanks @blchoy I think that SN15 is good enough to trigger the discussion at MIE which was the intent of this paper
