### ISSUE TITLE
Mandatory Element restrictions

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#178]
title:
* Limitation to the capability of IWXXM induced by current TAC templates 

Minimum and Maximum occurance of elements

temperature reporting
tropical cyclone

* see
    * #165 
    * #166 

IWXXM is bound by mandatory requirements
These could change in the future - MIE

Currently, limitation exists

Options & implications 
  (guidance for users of IWXXM 3.0)

**Comment by blchoy** [comment]
A paper was submitted as MIE/6 SN/09.
