### ISSUE TITLE
WAFC Implementation Proposal

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#179]
The WMO task team is working on WAFC implementation with an ambitious proposal aiming to produce a schema that is flexible and more maintainable, thus providing better sustainability for the standard.

This involves technical challenges in representation and validation that need to be addressed by the team.

Time scales:
  * propsed times for WAFCs
  * delivery time estimates
  * prototypes
  * limited validation options in earlier stages

**Comment by marqh** [comment]
Decision MIE/5-01 – IWXXM for low-level flights

**Comment by blchoy** [comment]
A paper was submitted as MIE/6 SN/12.
