### ISSUE TITLE
Georeferencing

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#180]
Action MIE/5-07 – Geo-referencing

Provide a paper to the IMP seeking advice on how to Geo-reference aeronautical and flight (AIXM & FIXM) information with meteorological (IWXXM) messages.

**Comment by marqh** [comment]
Decision MIE/5-04 – Map Projections

**Comment by marqh** [comment]
#173

**Comment by blchoy** [comment]
Rebecca Schultz had done some work on this and had submitted SN/04 to report progress.  I don't think the team needs to follow up on related MIE/5 decision and action.
