### ISSUE TITLE
Report to MIE October 2019 from TT-AvXML-8

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#181]
Scope:
* #162 
* Alignment with AIRM (decision 5/2 of Metp/4)
    * Decision MIE/5-05 – Harmonization of IWXXM with other XMs and AIRM
    * Action MIE/5-13 – Harmonization of IWXXM with other XMs and AIRM
* Action MIE/5-02 – Deletion policy for older versions of IWXXM
* Action MIE/5-06 – IWXXM SIGMET and AIRMET - investigate - we did: no
* Action MIE/5-08 – IWXXM Extensions #176  
    * states to publish, WMO/ICAO may add coordination
* IWXXM versions - for a message type, multiple versions if the format is the same
    * Decision MIE/5-02 – IWXXM Versions, Decision MIE/5-03 – IWXXM Versions
    * Action MIE/5-10 – IWXXM Versions #174 
* Change management
    * Action MIE/5-24 – IWXXM Development Process
    * Assessment of Amendment 79
    * Decision MIE/MRI Workshop-D7
    * Decision MIE/MRI Workshop-D8

**Comment by blchoy** [comment]
The report was submitted as SN/03 of MIE/6.
