### ISSUE TITLE
inclusion of XMI and HTML in Repo and Release

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#184]
XMI file and HTML output from EA (currently in IWXXM-modelling) in wmo-im/iwxxm and included in the releases 

1. move XMI and HTML to wmo-im/iwxxm
1. ask choy to update version number of model and schemas to 3.0.0RC4
1. add pull request checklist to remind proposers and reviewers that XMI HTML and XSD should change in synchronisation
1. git attribute is require to list directory for export and ignore

filter out directories, .. ... 
.gitattribute
```
externalSchema/ export-ignore
```

this also delivers #182

**Comment by blchoy** [comment]
Done.
