### ISSUE TITLE
Investigate Schematron Creation

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#185]
examine the work flow for management, creation and maintenance of the schematron file

examine the xmI 'constraint' free text information
examine style sheets in https://github.com/wmo-im/iwxxm-modelling 

consider structure and capability of schematron rules

investigate tool capabilities for auto-generation of schematron rules

**Comment by blchoy** [comment]
Sorry Mark, after a couple of years' time we are still not able to review the workflow for schematron file.  A more important thing to do is to spread out the understanding of how the IWXXM model (including the schematron rules) are developed and maintained and we have already taken the first step with the conduction of two workshops for team members.  We shall come back to this when our team is more mature in this respect.
