### ISSUE TITLE
Schematron rule Common.Report-4 is counting the length of extension across different reports in a bulletin

### ISSUE THREAD

**Issue by blchoy** [wmo-im/iwxxm#197]
The intention of schematron rule Common.Report-4 is to make sure that extensions will not overwhelm respective reports.  @mgoberfield reported that when he ran the rule over a bulletin with numerous reports with extensions the rule may fail (i.e. the total length of the extensions exceeded 5000 characters).  A closer look at the assertion itself revealed that the counting will cover all extension nodes in an XML document (//extension) and if the document is a bulletin the rule will treat all extensions as one instead of separately for individual report.

The solution is simple:  Just change all references to //extension to .//extension in the assertion.

As extension is not a mandatory item in Annex 3 (except possibly for US.  It would be nice if someone could advise related FAA requirements for TAC and IWXXM on supplementary information), and we will be soon including an upgrade to IWXXM to meet Amendment 79's changes, there is no reason for not postponing the fix until then.  

Views are most welcomed.

**Comment by mgoberfield** [comment]
I will see if I can get this information from the FAA.  The NTSB report recommended that the FAA make supplementary information available to all as they thought its absence from the METAR was a contributing factor to a fatal accident.

**Comment by blchoy** [comment]
Thanks Mark.  I think this is a good exercise to examine how we should react to reported issues especially on determining whether an urgent fix is required and if so/not how to proceed.

**Comment by mgoberfield** [comment]
Hi Choy, 
You wrote:

> As extension is not a mandatory item in Annex 3 (except possibly for US. It would be nice if someone could advise related FAA requirements for TAC and IWXXM on supplementary information)

Please see ICAO 19th Meeting of the Meteorology sub-group (MET SG/19) of APANPIRG [Working Paper 6](https://www.icao.int/APAC/Meetings/2015%20METSG19/WP08_WAFS%20Provider%20State%20AI.%206.2%20%20-%20METAR-SPECI.pdf) for FAA rationale. Is this sufficient for your intended goal?  The FAA is looking to see if there's additional, formal documentation to ICAO making US METAR/SPECI supplementary data mandatory.

**Comment by blchoy** [comment]
> The FAA is looking to see if there's additional, formal documentation to ICAO making US METAR/SPECI supplementary data mandatory

I think Para. 2.7 speaks for itself.  The next step would be to examine a typical IWXXM bulletin with extensions from the States.  Do you have one or can you make up one for the team to study?

**Comment by mgoberfield** [comment]
I can provide one.

**Comment by blchoy** [comment]
The patched was applied and will show up in the upcoming version.
