### ISSUE TITLE
Provide training topics to the CAeM Expert Team on Education, Training, and Competence

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#2]
During TT-AvXML-4 it was determined that training information should be provided to the ICAO/WMO CAeM that is meeting 30 November 2015 until 3 December 2015.

ref: https://software.ecmwf.int/issues/browse/AVXML-3

Created:
    29/Sep/15 6:46 PM 

Reporter:
    Aaron Braeckel

**Comment by braeckel** [comment]
@sforeman will contact Dimitar from the WMO side and ET-ETC was contacted regarding their needs for training relating to IWXXM.

**Comment by braeckel** [comment]
Until a request is made by ET-ETC this issue is closed.  We have previously informed this team that we can provide this information as needed
