### ISSUE TITLE
sigmet-VA-EGGX.tac has spurious altitude in the forecast

### ISSUE THREAD

**Issue by lcdunstan** [wmo-im/iwxxm#201]
sigmet-VA-EGGX.tac contains "OBS AT 1600Z SFC/FL550..." as well as "FCST 2200Z SFC/FL550..." but the XML only specifies the upperLimit for the observed AirspaceVolume. Shouldn't the second forecastPositionAnalysis AirspaceVolume also contain

```
<aixm:upperLimit uom="FL">550</aixm:upperLimit>
<aixm:upperLimitReference>STD</aixm:upperLimitReference>
```
?

**Comment by lcdunstan** [comment]
Or is the TAC wrong? I can't find where a forecast level is allowed in Annex 3.

**Comment by blchoy** [comment]
> Or is the TAC wrong? I can't find where a forecast level is allowed in Annex 3.

You are right the TAC itself is incorrect, and this was wrong since it first appear in earlier versions of IWXXM.  Thanks for informing and we will make the change.
