### ISSUE TITLE
Guidance on implementing TAF/METAR as per IWXXM 3.0

### ISSUE THREAD

**Issue by nishithjain** [wmo-im/iwxxm#204]
Hello All,

I am currently working on a migration of TAF to IWXXM 3.0 and getting many errors when I do validation using the schematron and schema files of IWXXM 3.0
I am new to this domain and need help in understanding the error messages and fixing them.

Error messages got when validated against schematron:
**TAF.TAF-7: in a non-empty baseForecast wxxm:surfaceWind is mandatory**
- What I understand is, if there is an element named 'baseForecast', then there should exists an element "MeteorologicalAerodromeForecast/surfaceWind" as its child.
- Where can I find the documentation for this? I mean there should be some documentation where it says the element 'surfaceWind' should be under baseForecast/MeteorologicalAerodromeForecast

**TAF.TAF-8: In a non-empty baseForecast when @cloudAndVisibilityOK is false prevailingVisibility and cloud are mandatory**
- Similar to the above error.

**MeteorologicalAerodromeForecast iwxxm:weather elements should be a member of http://codes.wmo.int/49-2/AerodromePresentOrForecastWeather**
- Can anyone explain what should be done here?
- Any documentation on implementing TAF with respect to IWXXM 3.0 would be helpful.

Also when I validate the TAF example file (https://schemas.wmo.int/iwxxm/3.0/examples/taf-A5-1.xml) against the schematron, I do get the following error...
**MeteorologicalAerodromeForecast iwxxm:weather elements should be a member of http://codes.wmo.int/49-2/AerodromePresentOrForecastWeather**

**Comment by blchoy** [comment]
Thank you.  Please provide feedback to or raise your question in Google group cbs-tt-avxml@wmo.int.

With regard to the validation error you have encountered with taf-A5-1.xml, I just double confirmed it works fine with my Oxygen XML Editor.  May I ask before you run the schematron rules have you downloaded all the necessary RDF files from the WMO Codes Registry?  There is a script in https://github.com/wmo-im/iwxxm/blob/master/bin/codeListsToSchematron.py which can help you download all the files in one go.

**Comment by blchoy** [comment]
Here nothing further so closing.
