### ISSUE TITLE
Validating TAF example file throws error when used with oxygen XML tool.

### ISSUE THREAD

**Issue by apssteam** [wmo-im/iwxxm#205]
Used tool (Oxygen xml) to validate example  xml against schematron and could see following errors.

**Example file used**: https://schemas.wmo.int/iwxxm/3.0/examples/taf-A5-1.xml
**Schematron** : iwxxm.sch 

**Error Message**:
- MeteorologicalAerodromeForecast iwxxm:weather elements should be a member of http://codes.wmo.int/49-2/AerodromePresentOrForecastWeather

**Comment by blchoy** [comment]
This is also included in #204 and will be handled there.
