### ISSUE TITLE
Validating the 'metar-NIL-collect.xml' example file gives error

### ISSUE THREAD

**Issue by nishithjain** [wmo-im/iwxxm#207]
Hello,

When I validated the **'metar-NIL-collect.xml'** example file (https://github.com/wmo-im/iwxxm/blob/master/IWXXM/examples/metar-NIL-collect.xml) against the "iwxxm3.0/iwxxm.xsd" using oxygen, I am getting the error "**Cannot find the declaration of element 'collect:MeteorologicalBulletin'.**".

Am I missing anything here?

Have one more doubt...
"collect:MeteorologicalBulletin" is applicable for only METAR NIL or it is applicable for non NIL case as well?

**Comment by blchoy** [comment]
> Am I missing anything here?

Yes you did.

May I invite you again to bring your questions to [cbs-tt-avxml](https://groups.google.com/a/wmo.int/forum/?hl=en&fromgroups#!forum/cbs-tt-avxml)?
