### ISSUE TITLE
schematron iwxxm.sch : some elements are not valid

### ISSUE THREAD

**Issue by dearith** [wmo-im/iwxxm#212]
Hi Team,

I'm using iwxxm.sch  to validate IWXXM 3 xml (using crux)

I found some mistakes:

1.  some xpath to the RDF files are not correct, e.g.:
`
document('codes.wmo.int-common-nil.rdf')/rdf:RDF/*/skos:member/ */@*[local-name()='about'] ) else( true() ) 
`
must be replaced by 
`
document('codes.wmo.int-common-nil.rdf')/rdf:RDF/descendant::*/skos:member/descendant::*/@*[local-name()='about'] ) else( true() ) 
`
 because skos:member is not a direct child of rdf:RDF andelements containing about attribute are not a direct child of skos:member

1. SIGMET.SIGMET-6 is not correct according to the error message : must be less than or equal to (so `eq` operator must be replaced by `le` operator) :
`
   <sch:pattern id="SIGMET.SIGMET-6">
      <sch:rule context="//iwxxm:SIGMET|//iwxxm:VolcanicAshSIGMET|//iwxxm:TropicalCycloneSIGMET">
         <sch:assert test="( if( string-length(@translationFailedTAC) eq 0 and exists(iwxxm:forecastPositionAnalysis//iwxxm:phenomenonTime/*) and exists(iwxxm:validPeriod/*) ) then( empty(index-of(for $i in iwxxm:forecastPositionAnalysis return number(translate($i//iwxxm:phenomenonTime/gml:TimeInstant/gml:timePosition,'-T:Z','')) eq number(translate(iwxxm:validPeriod/gml:TimePeriod/gml:endPosition,'-T:Z','')),false())) ) else( true() ) )">SIGMET.SIGMET-6: iwxxm:forecastPositionAnalysis//iwxxm:phenomenonTime must be less than or equal to iwxxm:validPeriod//endPosition</sch:assert>
      </sch:rule>
   </sch:pattern>
`
replaced by 
`
   <sch:pattern id="SIGMET.SIGMET-6">
      <sch:rule context="//iwxxm:SIGMET|//iwxxm:VolcanicAshSIGMET|//iwxxm:TropicalCycloneSIGMET">
         <sch:assert test="( if( string-length(@translationFailedTAC) eq 0 and exists(iwxxm:forecastPositionAnalysis//iwxxm:phenomenonTime/*) and exists(iwxxm:validPeriod/*) ) then( empty(index-of(for $i in iwxxm:forecastPositionAnalysis return number(translate($i//iwxxm:phenomenonTime/gml:TimeInstant/gml:timePosition,'-T:Z','')) le number(translate(iwxxm:validPeriod/gml:TimePeriod/gml:endPosition,'-T:Z','')),false())) ) else( true() ) )">SIGMET.SIGMET-6: iwxxm:forecastPositionAnalysis//iwxxm:phenomenonTime must be less than or equal to iwxxm:validPeriod//endPosition</sch:assert>
      </sch:rule>
   </sch:pattern>
`

See  iwxxm-modified.sch in my attache zip file

[iwxxm_modified.zip](https://github.com/wmo-im/iwxxm/files/4421890/iwxxm_modified.zip)

Regards

**Comment by blchoy** [comment]
Thank you for your feedback.

For (1), all options including `/*/`, `//` and `/descendant::*/` works on my oXygen XML Editor.  Interesting to know that it is not working on CRUX.  Will consider changing to a less confusing representation in the next update.

(2) is definitely a bug and will be corrected together with #208.

**Comment by blchoy** [comment]
For (1) no change has been made
For (2) it has been fixed in Version 3.0.1RC1 under #208
