### ISSUE TITLE
Amendment 79 to ICAO Annex 3

### ISSUE THREAD

**Issue by blchoy** [wmo-im/iwxxm#219]
This is a place holder for information and discussions on changes to IWXXM in relation to Amendment 79 to ICAO Annex 3.  An impact analysis with initial thinking on the changes to be made can be found [here](https://github.com/wmo-im/iwxxm/wiki/IA-2019_01).

**Comment by mgoberfield** [comment]
For VAA with the introduction of 'UNKNOWN's for some of these elements, our first attempt at how these changes are going to be represented in XML is a bit confusing to me (my usual state of mind).

For the **\<iwxxm:stateOrRegion\>** element, if its 'UNKNOWN', the suggested action is to use the 'nilReason' attribute and set it to http://codes.wmo.int/common/nil/unknown.
For the **\<iwxxm:eruptionDetails\>** element, despite being a 'StringWithNilReasonType', the suggested action is to **not** use the nilReason attribute when its 'UNKNOWN' but just use the string itself as the value.

Is 'SFC' to be used only when ash is re-suspended? If that's the case, then summitElevation nilReason set to inapplicable? Would be nice to have a footnote attached to 'SFC' to make this clear, if that's the case.

**Comment by blchoy** [comment]
Thanks @mgoberfield for bringing up.  I have been away for too long.

> For VAA with the introduction of 'UNKNOWN's for some of these elements, our first attempt at how these changes are going to be represented in XML is a bit confusing to me (my usual state of mind).

I think that depends on whether there is a need to make an element not null.  For example, while mentioning 'Tropical Cyclone NONAME' could be ambiguous, it is not possible to operate with 'Tropical Cyclone ""' at all.  In this case the tropical cyclone name is being used as an identifier so it has to be non-null.

Looking from this perspective, neither **\<iwxxm:stateOrRegion\>** nor **\<iwxxm:eruptionDetails\>** is being used as an identifier (you can challenge "State or Region" is but I think the more important identifier on a VAA is the location of the volcanic ash cloud) so if they are null it will not lose information. 

Views on the above interpretation are most welcome.

> Is 'SFC' to be used only when ash is re-suspended? Would be nice to have a footnote attached to 'SFC' to make this clear. If that's the case, then perhaps summitElevation nilReason set to inapplicable?

I am not too sure SFC in **\<iwxxm:summitElevation\>** can be represented by a null element and a nilReason "inapplicable".  A formal method is to change this element from simple type to a complex type with the original summit elevation as one element and a boolean attribute to indicate whether it is at SFC if the element has a null value.  For example `<iwxxm:summitElevation isSFC="true"\>`.  Dirty but workable.

**Comment by mgoberfield** [comment]
I see that you revised the wiki [entry](https://github.com/wmo-im/iwxxm/wiki/IA-2019_01).

Your comment suggests to me, then, that there is an overuse of StringWithNilReason types within the schemas. Would that be correct? If so, perhaps as part of the 3.1 update, those elements of StringWithNilReason types should be looked at more carefully and consider changing some to be ordinary character strings.

With regards to VAA summitElevation (of type LengthWithNilReason) potentially being set to 'SFC', at the time of my original comment, I had to come up with a means (albeit, indirect) to indicate that with the existing 3,0 schema.  Since you deem that not a viable proposal/solution, I await the new complex type for summitElevation in a later version.

I will withdraw my PR on the IWXXM model.

**Comment by blchoy** [comment]
> Your comment suggests to me, then, that there is an overuse of StringWithNilReason types within the schemas. Would that be correct? If so, perhaps as part of the 3.1 update, those elements of StringWithNilReason types should be looked at more carefully and consider changing some to be ordinary character strings.

A quick check of the use of StringWithNilReason confirmed my memory that it had been cautiously used so far (e.g. sequenceNumber and cancelledReportSequenceNumber in SIGMET).  The only thing is that not all of them are explicitly described in the TAC-to-XML-Guidance.txt document.

> With regards to VAA summitElevation (of type LengthWithNilReason) potentially being set to 'SFC', at the time of my original comment, I had to come up with a means (albeit, indirect) to indicate that with the existing 3,0 schema. Since you deem the use of nilReason not a viable proposal/solution, I await the new complex type for summitElevation in a later version.

Another way of putting different types of information into a single element is to define an UML Class with stereotype <<Union>> which will be serialised as `<xsd:choice>` in XML schema:

![image](https://user-images.githubusercontent.com/30064374/104112664-9cd80000-532c-11eb-9b88-110b6bcefab6.png)

I used to have a discussion with Aaron and it was not his preferred representation.  I cannot recall the exact reason for his choice but from a data perspective now you have an element which can either be a numerical value or a string and that is going to introduce issues in decoding and storage.

**Comment by mgoberfield** [comment]
I will ping my contact at Washington VAAC to see what they have to say about the discrepancy.

**Comment by blchoy** [comment]
I think all the changes involving Amendment 79 should have been taken care of right now.  This issue is hereby closed.
