### ISSUE TITLE
all IWXXM reports to be in COLLECT containers

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#22]
Annotate the documentation of IWXXM to record that ICAO requires all IWXXM reports to be packaged in a COLLECT container.

WG-MIE decided that COLLECT should be used for all IWXXM reports, even for single reports.

**Comment by braeckel** [comment]
Collect should be mandatory for AMHS communications, but those trying to use a WFS probably want a different solution so they can have iwxxm:METAR as the top-level featureType.  The use of both should be considered so IWXXM and Collect can carry the relevant information across both communication methods

**Comment by braeckel** [comment]
This change may also suggest that all of the examples (TAC and XML) should be updated to include WMO bulletins and corresponding Collect elements

**Comment by marqh** [comment]
This requirement shall be documented on the wiswiki and details of the two different schemas, one with COLLECT and one without provided.

For all AMHS communications, including single IWXXM reports, shall be packaged in a COLLECT container

This update should be considerd for the next version of WMO 306

**Comment by marqh** [comment]
section 6.2.2 within ICAO doc: 8896 (Manual of Aeronautical Practice) could be requested to be updated to include this requirement

**Comment by braeckel** [comment]
WMO wiki should be updated to include text similar to: 
"COLLECT shall be used on ATN networks in similar manner to how WMO Bulletins are used with TAC.  For example, when single IWXXM messages are distributed on the ATN they shall be wrapped in a COLLECT element as with TAC messages"

**Comment by blchoy** [comment]
I will add some COLLECT examples based on some of the existing sample messages.

**Comment by blchoy** [comment]
Committed validated IWXXM bulletin examples (METAR, TAF and SIGMET) to the master branch (I intended to push to a new branch but failed :( ).

**Comment by blchoy** [comment]
As discussed with Aaron, I have undone the committed IWXXM bulletin examples.  Instead, I have created a branch, committed a new set of files and initiated a pull request to Aaron, Mark and Steve to try out the review arrangement.
