### ISSUE TITLE
IWXXM SWX. Day light side and coordinates accuracy

### ISSUE THREAD

**Issue by moryakovdv** [wmo-im/iwxxm#222]
Hello. 
Converting the SWX Advisory I'm facing with DAYLIGHT SIDE. As it mentioned in TAC-to-XML-Guidance.txt we should provide lat/lon of the sub-solar point as a center of the area for the given date-time.
AFAIK, the latitude of the sub-solar point is the same as solar declination for the given time(correct me, please, if I'm wrong). In common engineering calculation we calc this value for the given **day**. So, the latitude changes when the day changes. But, in our IWXXM examples the latitude changes **during** the day.  So I wonder is the accuracy of latitude enough (daily changes) when we use the common approach or one should use more precise calculations to inject **hour** correction?
Might be we should mention it in guidance? 

Regards,
Dmitry

**Comment by blchoy** [comment]
Finding the sub-solar point at a particular time is a well known problem and there are [details](https://www.esrl.noaa.gov/gmd/grad/solcalc/calcdetails.html) on calculating the location of the point.  I would suggest we go for a more precise calculation.

If you think the guidance is not clear enough we can update this in version 3.0.1.

**Comment by blchoy** [comment]
Reading the guidance again I believe the message should be clear enough.  Until there are better suggestions this issue will be closed.
