### ISSUE TITLE
Testing SIGMET's FIR boundaries

### ISSUE THREAD

**Issue by moryakovdv** [wmo-im/iwxxm#224]
Hello.
During testing SIGMET's TAC-to-IWXXM conversion I'd like to clarify examples. 
If we use fake FIR (YUDD SHANLON) we can't determine it's coordinates in, say, shape file, since FIR doesn't exist. 
So, I can't check my gis-tool for correctness of provided intersection coordinates.
Is it possible to include real verified example of TAC and corresponding IWXXM SIGMET ?

**Comment by mgoberfield** [comment]
Responded on the CBS TT-AvXML forum.

**Comment by moryakovdv** [comment]
Thank you, Mark. Now I can use your files as reference
