### ISSUE TITLE
RDF for CloudAmountReportedAtAerodrome. Typo in SCT

### ISSUE THREAD

**Issue by moryakovdv** [wmo-im/iwxxm#225]
There is a typo(a small **s**) in SCT's skos:notation tag in CloudAmountReportedAtAerodrome.rdf
[link](http://codes.wmo.int/49-2/CloudAmountReportedAtAerodrome/SCT)
This can be an issue if one uses skos:notation as a key in key-value structures.
see [Section 6](https://www.w3.org/TR/skos-reference/#notations)

@marqh, could you please fix it?

**Comment by blchoy** [comment]
![image](https://user-images.githubusercontent.com/30064374/82769456-3ff40c00-9e67-11ea-927d-888cc291ceb5.png)

You have eagle eyes, Dimitry.  :)

**Comment by moryakovdv** [comment]
> ![image](https://user-images.githubusercontent.com/30064374/82769456-3ff40c00-9e67-11ea-927d-888cc291ceb5.png)
> 
> You have eagle eyes, Dimitry. :)

No, I have got failed test =)

**Comment by mgoberfield** [comment]
Submitted a [PR](https://github.com/wmo-im/IWXXMCodeLists/pull/7) to wmo-im/IWXXMCodeLists
