### ISSUE TITLE
Wrong limit in SpaceWeatherAdvisory examples?

### ISSUE THREAD

**Issue by ilkkarinne** [wmo-im/iwxxm#227]
In example [spacewx-A2-4.tac](https://github.com/wmo-im/iwxxm/blob/master/IWXXM/examples/spacewx-A2-4.tac#L7) the TAC states:
`ABV FL340`

But the [spacewx-A2-4.xml](https://github.com/wmo-im/iwxxm/blob/master/IWXXM/examples/spacewx-A2-4.xml#L49) AirspaceVolume has:
```
<aixm:upperLimit uom="FL">350</aixm:upperLimit>
<aixm:upperLimitReference>STD</aixm:upperLimitReference>
```

As far as I understand the [AIXM AirspaceVolume](http://www.aixm.aero/sites/aixm.aero/files/imce/AIXM51HTML/AIXM/Class_AirspaceVolume.html) the IWXXM value corresponding to the provided TAC limit should be
```
<aixm:lowerLimit uom="FL">340</aixm:upperLimit>
<aixm:lowerLimitReference>STD</aixm:upperLimitReference>
```

**Comment by blchoy** [comment]
Both TAC and XML are wrong in one way or the other.

First of all, the flight level in TAC should be FL350:
![image](https://user-images.githubusercontent.com/30064374/88824994-9aa83c00-d1f9-11ea-9c76-314db06bc302.png)

Secondly, you are right with regard to the way aixm:AirspaceVolume should be used, viz:
```
<aixm:lowerLimit uom="FL">350</aixm:upperLimit>
<aixm:lowerLimitReference>STD</aixm:upperLimitReference>
```
which indicates the phenomenon has a lower bounding surface at FL350 and unspecified upper bounding surface.

**Comment by blchoy** [comment]
All three Space Weather Advisory examples have been aligned with Amendment 78 to ICAO Annex 3 in Version 3.0.1RC1.
