### ISSUE TITLE
The validation failed when the internet is turned off

### ISSUE THREAD

**Issue by caoshansh** [wmo-im/iwxxm#228]
The code in checkGMLFiles.py couldn't validate the elements when the internet is turned off, the related part is shown as below:
        response = urllib2.urlopen(xlinkTarget)
        code = response.getcode()
        content = response.read()

The "rdf" files have been downloaded, so it should be found from the "rdf" files, but uses "urlopen" to check the element.

**Comment by blchoy** [comment]
bin/checkGMLFiles.py is part of the CI process to check if the required codeList references are indeed available online.  Of course you can check the RDF files downloaded but we believe an end-to-end test is more appropriate for our purpose.

Thanks for pointing out anyway.
