### ISSUE TITLE
Correct nilReason for minimum visibility direction

### ISSUE THREAD

**Issue by moryakovdv** [wmo-im/iwxxm#229]
Hello.
If minimum visibility is mentioned without a direction what nilReason should be used to indicate that?
Example metar:
METAR WIII 232230Z 18004KT 2400 0600 OVC013 27/15 Q1014

[Here](https://github.com/moryakovdv/iwxxmConverter/pull/9) is a discussion about link to _missing_. 
Could you please confirm?

**Comment by mgoberfield** [comment]
FWIW, I use the 'missing' concept in this case, since I cannot discern another reason for why it would be missing from just the TAC alone.

**Comment by moryakovdv** [comment]
Thanks, Mark.
