### ISSUE TITLE
Missing Entries in 49-2/AerodromePresentOrForecastWeather

### ISSUE THREAD

**Issue by blchoy** [wmo-im/iwxxm#232]
For completeness, this makes reference to [an issue](https://github.com/wmo-im/IWXXMCodeLists/issues/2) posted on the wmo-im/IWXXMCodeLists repository.

**Comment by blchoy** [comment]
Interestingly, all of them can be found under codes.wmo.int/306/4678, viz:

[-SS](http://codes.wmo.int/306/4678/-SS)
[-DS](http://codes.wmo.int/306/4678/-DS)
[+FC](http://codes.wmo.int/306/4678/+FC)

Apparently there are missing aliases under http://codes.wmo.int/49-2/AerodromePresentOrForecastWeather to these items in http://codes.wmo.int/306/4678.

**Comment by mgoberfield** [comment]
Submitted a [PR](https://github.com/wmo-im/IWXXMCodeLists/pull/5) to wmo-im/IWXXMCodeLists
