### ISSUE TITLE
Attribute cloudAndVisibilityForecast in MeteorologicalAerodromeForecast in TAF should be optional

### ISSUE THREAD

**Issue by blchoy** [wmo-im/iwxxm#233]
@jkorosi reported that as attribute cloudAndVisibilityOK is not optional, he will have to determine in both the main and change groups of a TAF boolean values for this attribute which is not necessary in some cases.  For example:

```
TAF FAOR 062200Z 0700/0806 18010KT CAVOK TX12/0713Z TN07/0703Z
    BECMG 0700/0702 BKN012
    PROB40 TEMPO 0702/0706 3500 BR BKN008
    PROB30 TEMPO 0703/0705 0800 FG VV002
    BECMG 0703/0705 11012KT
    BECMG 0710/0712 07010KT BKN030
    PROB30 TEMPO 0715/0721 5000 -SHRA
    BECMG 0722/0724 01012KT
```

Only the main group needs to specify cloudAndVisibilityOK="true".

If we follow TAC strictly cloudAndVisibilityOK should either be true or not mentioned but never be false.  Having said that, for the change group "BECMG 0700/0702 BKN012" there is no harm if one also mention cloudAndVisibilityOK="false".

In any case, as suggested by @jkorosi, we will be making this attribute optional in the next update.  Note that the description of TAF.TAF-8 should also be changed: "TAF.TAF-8: In a non-empty iwxxm:baseForecast when @cloudAndVisibilityOK is false _or empty_ iwxxm:prevailingVisibility and iwxxm:cloud are mandatory"

**Comment by mgoberfield** [comment]
> Only the main group needs to specify cloudAndVisibilityOK="true".

??  what is 'main group'  -- you mean "baseForecast"?

Perhaps you meant to say that the cloudAndVisibilityOK='true' appears whenever CAVOK is mentioned in the forecast?

TAF LLBG 141708Z 1418/1518 29005KT 9999 FEW020
     BECMG 1420/1422 16005KT SCT018
     PROB40 1500/1506 BKN015
     **BECMG 1507/1509 27010KT CAVOK**
     BECMG 1514/1516 16004KT SCT018
     TX34/1511Z TN25/1503Z=

Several TAF schematron rules will need to be revised since it assumes the cloudAndVisibilityOK attribute will always be there in the baseForecast and changeForecast groups.

V/R,

mark

**Comment by blchoy** [comment]
This was implemented in IWXXM 2021-2RC1.
