### ISSUE TITLE
Missing Vertical Visibility

### ISSUE THREAD

**Issue by moryakovdv** [wmo-im/iwxxm#234]
Hello all,
When VV is not observed in METARs there is a token VV///
But when we try to convert it into XML the following tag appears:
`<iwxxm:verticalVisibility nilReason="http://codes.wmo.int/common/nil/notObservable">0.0</iwxxm:verticalVisibility>`
The `0.0` appears because of LengthWithNilReason has field `value` with `double` data type.
I wonder if this is correct to have `0.0` in the tag value in this case.
BTW, which of nilReasons is more appropriate for this : _missing_, _notObservable_ or _notDetectedByAutoSystem_ ?

Thanks for comments.

**Comment by mgoberfield** [comment]
Answer: https://github.com/wmo-im/iwxxm/blob/4d13795fba912ff6fa4d348c5232462c81f5b672/IWXXM/examples/TAC-to-XML-Guidance.txt#L49

**Comment by blchoy** [comment]
@mgoberfield is right.  We have discussed this in #19.  This is a natural consequence of how GML and its XML implementation is defined and I don't see an urgent need to get around.  But I am open to comments and suggestions.

**Comment by blchoy** [comment]
As there is no further comments I am closing this issue right now.  How to make an element nil with the inclusion of a nilReason is definitely something to be put into the future guidance material (if any).
