### ISSUE TITLE
Discontinue TravisCI for project

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#239]
TravisCI will [no longer support](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) 'open-source' projects like this one. A CI replacement should be considered.

**Comment by moryakovdv** [comment]
Hello.
If CI has not been chosen yet, the Jenkins might be an option. As far as I know, it has no problems with Open source, GIT and other stuff.

**Comment by blchoy** [comment]
Thanks for informing.  Let me take a look at this.

**Comment by mgoberfield** [comment]
While I have not investigated Jenkins in GitHub environment, I have used GitHub Actions for CI in my other projects.
For your consideration, I have submitted a [PR](https://github.com/wmo-im/iwxxm/pull/240) as a possible replacement.

**Comment by mgoberfield** [comment]
A follow-up posting [here](https://blog.travis-ci.com/oss-announcement) suggests that open-source projects will continue to remain free. If that's truly the case, then this issue can be closed without changes.

**Comment by blchoy** [comment]
This was implemented since IWXXM 2021-2RC1.
