### ISSUE TITLE
Misspelled attribute

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#246]
https://github.com/wmo-im/iwxxm/blob/52a7cda609920be111f6b38df2abab6c6c9a5c4c/IWXXM/common.xsd#L35

Unintended change from branch master.  Missing the second 'i' in permissibleUsageSupplementary

**Comment by blchoy** [comment]
Thank you and you have good eye-sight!  I have fixed the stuff at model level and re-committed just now.
