### ISSUE TITLE
METAR/SPECI Readiness

### ISSUE THREAD

**Issue by amilan17** [wmo-im/iwxxm#248]
# Branch
https://github.com/wmo-im/iwxxm/tree/FT2021-2_METAR/SPECI

# Summary and Purpose
Validate for public consultation readiness.

# Related Issues
#203 
https://github.com/wmo-im/iwxxm-codelists/issues/2

**Comment by blchoy** [comment]
@jkorosi mentioned that it would be nice to also include how SNOCLO should be described in the notes of the schema to align the descriptions in WMO No.306 Vol.I.3 and the TAC-to-XML Guidance.  The following is the part of the schema involved:
```
<element nillable="true" name="runwayState" minOccurs="0" maxOccurs="unbounded">
	<annotation>
		<documentation>When runways are affected by snow, slush, or other contaminants, a runway state report for each runway in use is required.
There is no maximum number of runway states that can be reported.  This may be changed in a future amendment.
		</documentation>
	</annotation>
	...
```
and this is what is being written in the guidance:
```
SNOCLO - Runways closed due to snow
  When all runways are closed due to snow, this shall be indicated with a "runwayState" with a nilReason of "http://codes.wmo.int/common/nil/inapplicable"
```
I think we could simply copy the line in the guidance into the schema.  Comments?

**Comment by amilan17** [comment]
OK for PC with outstanding items: Improve descriptions in iwxxm:runwayState

**Comment by blchoy** [comment]
Implementation completed in IWXXM 2021-2RC1.
