### ISSUE TITLE
TAF Readiness

### ISSUE THREAD

**Issue by amilan17** [wmo-im/iwxxm#249]
# Branch

https://github.com/wmo-im/iwxxm/tree/FT2021-2_TAF

# Summary and Purpose

Validate for public consultation readiness.

# Related Issues

#233

**Comment by amilan17** [comment]
Ok for PC. Re-version as 3.0.1, because it's just a minor change that is backwards compatible.

**Comment by blchoy** [comment]
Implementation completed in IWXXM 2021-2RC1.
