### ISSUE TITLE
Tropical Cyclone Advisory Readiness

### ISSUE THREAD

**Issue by amilan17** [wmo-im/iwxxm#252]
# Branch
https://github.com/wmo-im/iwxxm/tree/FT2021-2_Tropical_Cyclone_Advisory

# Purpose
Validate for public consultation readiness

# Related Issues
#166 
#241 
#244

**Comment by mgoberfield** [comment]
IMO, the documentation/description of the new enumeration type for TC intensity change is misleading. Annex 3 Amd 79 for the advisory states that the intensity change is "Changes of maximum surface wind speed at the time of observation" so the value is based on a comparison of the previous state of the TC and what is happening at the moment of the observation.  IMO, it is not a forecast of intensity change (and, for what it is worth, NHC specialists have said as much to me).  Thus, "TropicalCycloneExpectedIntensityChangeType", I feel, is misleading.  I suggest removing the word "Expected" and remove the word 'forecast' from the description of each enumerated value.

For your consideration:
```xml
	<simpleType name="TropicalCycloneIntensityChangeType">
		<annotation>
			<documentation>Change in intensity at the time of the observation.</documentation>
		</annotation>
		<restriction base="string">
			<enumeration value="NO_CHANGE">
				<annotation>
					<documentation>No change in intensity</documentation>
				</annotation>
			</enumeration>
			<enumeration value="WEAKENED">
				<annotation>
					<documentation>Tropical storm has weakened</documentation>
				</annotation>
			</enumeration>
			<enumeration value="INTENSIFIED">
				<annotation>
					<documentation>Tropical storm has intensified</documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>```

It would be good to get BOM's or JMA's opinions on this if there are still some questions about its interpretation.

Respectfully submitted.

**Comment by amilan17** [comment]
OK for PC after the following changes are made to schema, schematron and examples. 

*   add notes on the documentation in the element for CB clouds in the schema. 
*   change ExpectedIntensityChangeType to TropicalCycloneIntensityChangeType based on Mark's suggestion

**Comment by blchoy** [comment]
A slight change to the text is suggested: Instead of saying "Tropical storm has intensified/weakened" it would be safer to say "Tropical cyclone has intensified/weakened".

**Comment by blchoy** [comment]
Implementation completed in IWXXM 2021-2RC1.
