### ISSUE TITLE
Space Weather Advisory Readiness

### ISSUE THREAD

**Issue by amilan17** [wmo-im/iwxxm#254]
# Branch
https://github.com/wmo-im/iwxxm/tree/FT2021-2_Space_Weather_Advisory

# Purpose
to prepare for public consultation

# Related Issues
#241 
/wmo-im/iwxxm-codelists/issues/4

**Comment by mgoberfield** [comment]
Is 3.0.1 the intended version for this release?  For comparison, the TAF schema has one very small change and is backward compatible, yet it's version 3.1.0.  Just making sure the versioning rules are being implemented consistently.  😄

**Comment by blchoy** [comment]
> Is 3.0.1 the intended version for this release? For comparison, the TAF schema has one very small change and is backward compatible, yet it's version 3.1.0. Just making sure the versioning rules are being implemented consistently. 😄

I have copied this comment to the TAF branch as it is TAF which needs a change in version number, not SWA.

**Comment by blchoy** [comment]
Implementation completed in IWXXM 2021-2RC1.
