### ISSUE TITLE
Non-existent NIL reason in guidance

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#270]
It was really an inappropriate selection for a nil reason, @blchoy!

https://github.com/wmo-im/iwxxm/blob/8383493c84c63fad342b0f3fbc24070cf7394160/IWXXM/examples/TAC-to-XML-Guidance.txt#L206

Of the fixes I could think of, all of them were [inapplicable](http://codes.wmo.int/common/nil/inapplicable) for this situation.😄

**Comment by blchoy** [comment]
Haha, the only thing inappropriate is the nilReason itself!  Will fix.

**Comment by blchoy** [comment]
I think we have finished this one and is therefore closed.

**Comment by mgoberfield** [comment]
The invalid value for nilReason is still there in RC2

https://github.com/wmo-im/iwxxm/blob/6136d033723b85cb193a2adbddbd040ee5c8dd8f/IWXXM/examples/TAC-to-XML-Guidance.txt#L206

Thus, I do not think it's closed yet.  In the case of CB location set to NIL, this information is conveyed in XML with nilReason set to  [inapplicable](http://codes.wmo.int/common/nil/inapplicablel)

**Comment by blchoy** [comment]
> Thus, I do not think it's closed yet. In the case of CB location set to NIL, this information is conveyed in XML with nilReason set to inapplicable

My apologies for overlooking this one.  This is now fixed with commit https://github.com/wmo-im/iwxxm/commit/3bff2a4b1e1ec7721ea083e6ecfc14a382fd0809
