### ISSUE TITLE
[iwxxm-collect] conflicting element names in v3.1 (rc)

### ISSUE THREAD

**Issue by kcris** [wmo-im/iwxxm#279]
Trying to consume the 2021-2RC1 iwxxm schemas 
(via java generator) 
I noticed that when loading iwxxm-collect.xsd conflicting element names are detected

for example

this is part of wafssigwxfc.xsd
```xml
	<element name="Volcano" type="iwxxm:VolcanoType" substitutionGroup="gml:AbstractGML"> ...
```

and this is part of phenomena.xsd
```xml
        <element name="Volcano" type="metce:VolcanoType" substitutionGroup="gml:AbstractFeature"> ...
```

These xsd files are used together and elements are in the same targetNamespace, so this is a problem.

And there are many such conflicts in these xsd files.

These must be fixed in the xsd, not in the client code.

Thanks

ps: another issue is that the original `schemaLocation` in these xsd files is not a real url (http://schemas.wmo.int/iwxxm/2021-2RC1/iwxxm.xsd). I know this is before the release, but it means schemas are not easily testable without prior patching.

**Comment by kcris** [comment]
no, the targetNamespace is not the same, my bad

**Comment by blchoy** [comment]
They are different.

wafssigwxfc.xsd is part of IWXXM while phenomena.xsd is part of METCE, and they are under different namespaces (viz http://icao.int/iwxxm/2021-2 and http://def.wmo.int/metce/2013).

You are right as the path of the java-bindings should be properly managed.
