### ISSUE TITLE
Incorporate common XML approaches

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#28]
The cross-XM coordination discussions have led to several recommendations regarding versioning, deprecation, and namespaces.  Consider the use of each of the policies described in https://ext.eurocontrol.int/aixm_confluence/display/XMWIP/Overview.

Note that the namespace policy may be particularly problematic as it would suggest something like http://www.iwxxm.aero/schema/{X}.{Y} instead of http://icao.int/iwxxm/{X}.{Y}

**Comment by braeckel** [comment]
This is a longer-term, ongoing activity and as such is not appropriate for the 3.0RC1 release

**Comment by blchoy** [comment]
Having said that, we may want to indicate which parts we will follow in some places.  Perhaps the Github Wiki?

**Comment by blchoy** [comment]
A paper was presented on this topic at the joint ICAO WG-MIE and WG-MRI workshop and the participants agreed that the existing namespace for IWXXM, viz http://icao.int/iwxxm/X.Y (where X and Y are major and minor version numbers), would continue to be used.
