### ISSUE TITLE
 Changes to the template for advisory information on volcanic ash (VAA)

### ISSUE THREAD

**Issue by amilan17** [wmo-im/iwxxm#307]
### Initial request

1. Relevant discussions at METP/5:

    * (Report to Agenda Item 7. Para. 7.1.7) The meeting further noted with the elevation of the VONA to a recommended practice, the work stream agreed to remove the aviation colour code from the VAA template, to reduce the likelihood of conflicting information and any confusion when an aviation colour code is not able to be provided within the VAA, due to the volcano not being able to be monitored adequately...
     * (Report to Agenda Item 7. Para. 7.1.9) The meeting was further informed that the work stream discussed improvement of VAA template to more clearly indicate available information in an initial VAA (issued in the initial stages of a new eruption, when dispersion model information may not be available) and re-broadcast VAA (refers to another VAAC’s VAA that describes volcanic ash affecting area of responsibilities of the both VAACs)...
1. See the extracted [Template for advisory information on volcanic ash](https://github.com/blchoy/iwxxm-testbedOne/files/6875300/Proposed_TAC_Template_for_VAA.pdf) from the proposed text in working paper METP/5-WP/4102.

1. Other changes mentioned in METP/5-WP/4102 include:

    a) Renaming the VAA element ‘Summit Elevation’ to ‘Source Elevation’ to better describe the element contents (as the vent emitting volcanic ash may not be at the summit of the volcano), along with new information under Detailed Content to describe its use.
    b) Addition of a mandatory height reference for the Source Elevation – AMSL or BLW MSL, plus inclusion of footnote to indicate latter is to be used only for undersea volcanoes (as there are no volcano vents inland that are below AMSL included in the Smithsonian Global Volcanism Program Holocene volcano list).
    c) Removal of the option ‘SFC’ for the Source Elevation, as the elevation of a volcanic ash source must be described in reference to MSL for use by VAAC dispersion models, or otherwise indicated as UNKNOWN. For re-suspended volcanic ash, the Detailed Content notes indicate the average height of volcanic ash field is to be used.
    d) Inclusion of NOT PROVIDED in the Time of observation of ash and Observed ash cloud element templates, to facilitate a VAAC issuing a re-broadcast VAA that simply refers to the neighbouring VAAC’s VAA that describes the area of volcanic ash that affects both VAAC’s areas of responsibility – and does not have to re-produce elements of that VAA.
    e) Inclusion of NOT AVBL in the Observed ash cloud element template, to facilitate a VAAC issuing an initial VAA that simply informs users an eruption has occurred and more information will follow soon, as OBS or FCST volcanic ash may not yet be available.
Removal of an example for the Observed ash cloud element which is no longer permissible (correcting an error).
    f) Minor changes including editorial changes to the footnote for using TEST and EXER, adding a footnote to clarify the limit to the coordinates and the projection of straight lines when sending in abbreviated plain language (sometimes referred to as TAC), updating the VAA example to remove the aviation colour code, and updating example date-time groups.
1. See [Example A7-2](https://github.com/blchoy/iwxxm-testbedOne/files/6875533/VONA_and_VAA_Examples.pdf).

### Amendment details

As described in the [following post](https://github.com/wmo-im/iwxxm/issues/307#issuecomment-1674810164).

### Requestor(s)

METP / Amendment 81

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3

**Comment by blchoy** [comment]
The following class diagram indicated the proposed changes to be made:

![Context Diagram Volcanic Ash Advisory](https://github.com/wmo-im/iwxxm/assets/30064374/f1e84e6b-de64-4f24-8f4a-b9e22b48af02)

These include the change of attribute summitElevation to sourceElevation, and the removal of attribute colourCode.

**Comment by blchoy** [comment]
See [_Table A7-2. Template for advisory information on volcanic ash_](https://github.com/wmo-im/iwxxm/files/10774997/Table_A7-2.pdf) for the revised TAC template and [_Example A7-2_](https://github.com/wmo-im/iwxxm/files/10774996/Example_A7-2.pdf) for the updated example.

**Summary of changes**

1. **Element 8 - Source elevation**:
   * Element iwxxm:submitElevation has been renamed to iwxxm:sourceElevation.
   * iwxxm:sourceElevation is of type iwxxm:DistanceWithNilReason with positive values meaning elevation above MSL and negative values elevation below MSL. The notes of iwxxm:sourceElevation has been revised accordingly.

2. **Element 11 (old) - Colour code**:
   * Element iwxxm:colourCode has been removed.

3. **Element 12 - Time of observation (or estimation) of ash**:
   * The notes of iwxxm:phenomenonTime has been revised to include information on representing NOT PROVIDED.

4. **Element 13 - Observed or estimated ash cloud**:
   * Enumeration VolcanicAshObservedOrEstimatedStatus has been revised to support representation of NOT AVBL and NOT PROVIDED.

5. The notes in all elements of iwxxm:VolcanicAshAdvisory have been revised to improve the descriptions involving the use of full URL like http://codes.wmo.int/common/nil/unknown for nilReason.

6. In view of the changes the version number for VAA has been advance from 3.1.0 to 3.2.0.

**Comment by blchoy** [comment]
Included in IWXXM 2025-2RC1.
