### ISSUE TITLE
Changes to Space Weather Information

### ISSUE THREAD

**Issue by amilan17** [wmo-im/iwxxm#308]
### Initial request

1. Relevant discussion at METP/5:

 (METP/5 - WP/2302, Appendix C, PANS-MET, Appendix 7) Rationale for the proposed revisions to Annex 3 and PANS-MET:
    a) Moved the “Intensity” from the “Effect” line to the “Observed” and “Forecast” lines, which allows for the intensity to change within an advisory as well as allows for multiple intensities, thus reduces the number of advisories in effect at one time.
    b) Allow for an updated advisory to replace up to four existing advisories.
    c) Added “NIGHTSIDE” and renamed “DAYLIGHT SIDE” to “DAY SIDE”
    d) Updated the template and examples in the Table.
    e) Removed the “minutes” from latitude and longitude since this accuracy is beyond the state of the science.
    f) Editorial changes to footnote 1 for TEST and EXER.
    g) Clarified that altitude information only applies to radiation events.
    h) Clarified that the end point of a polygon is a repeat of the start point.
    i) With the agreement that MET products in IWXXM form are not constrained to limits of coordinates, made note that advisories disseminated in abbreviated plain language should keep coordinates to a minimum of seven. This same note has been added to other similar MET products.
1. See the extracted [Proposed amendments to the restructured Annex 3](https://github.com/blchoy/iwxxm-testbedOne/files/6876908/Proposed_TAC_Template_for_SWA.pdf) in working paper METP/5-WP/2302.

1. See [Examples A7-3 to A7-5](https://github.com/blchoy/iwxxmtestbedOne/files/6876914/SWA_Examples.pdf).

### Amendment details

As described in the [following post](https://github.com/wmo-im/iwxxm/issues/308#issuecomment-1674835291).

### Requestor(s)

METP / Amendment 81

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3

**Comment by blchoy** [comment]
See [_Table A7-3. Template for advisory message for space weather information_](https://github.com/wmo-im/iwxxm/files/10774993/Table_A7-3.pdf) for the revised TAC template and [_Examples A7-4 and A7-5_](https://github.com/wmo-im/iwxxm/files/10774992/Example_A7-4_A7-5.pdf) for the updated examples.

**Summary of changes made (see [committed changes](https://github.com/blchoy/iwxxm/commit/165031f66538f0eef7d3ad4e476fcc872e713725))**

1. **Element 5 - Space weather effect**:
   * A new enumeration SpaceWeatherEffect containing only the effects but not associated intensities has been created.

2. **Element 7 - Number(s) of advisories being replaced**:
   * The multiplicity of iwxxm:replacedAdvisoryNumber has been changed from [0..1] to [0..4].

3. **Element 8 - Observed or expected space weather event**:
   * A new classes SpaceWeatherIntensityAndRegion has been added to represent intensity and region at the same time.
   * Codelist iwxxm:SpaceWeatherLocation has been amended (DAYLIGHT_SIDE -> DAYSIDE and add NIGHTSIDE). 
   * The notes of iwxxm:SpaceWeatherLocation has been revised to remind that altitude of space weather phenomena shall only apply to radiation events.

4. In view of the changes the version number for SWA shall advance from 3.0.1 to 3.1.0.

**Comment by blchoy** [comment]
Included in IWXXM 2025-2RC1.
