### ISSUE TITLE
Relaxation of TAC constraints on IWXXM

### ISSUE THREAD

**Issue by amilan17** [wmo-im/iwxxm#309]
### Initial request

. Relevant discussion at METP/5:

   * (Report to Agenda Item 6. Para. 6.15) The Panel noted that the WG-MIE developed the proposed changes ..., including ... a few changes in METAR/SPECI that removes constraints related to the number of RVR and inclusion of tenths of temperature and dew point, ... It was noted that the removal of the IWXXM constraints does not form a new requirement but is intended to create the capacity, to enable States that wish to do so, to provide this additional information in IWXXM form.
1. See the extracted [Proposed amendments to the restructured Annex 3](https://github.com/blchoy/iwxxm-testbedOne/files/6875914/Proposed_TAC_Constraint_Relaxation.pdf) in working paper METP/5-WP/3301.

. In the proposed Amendment 81, the following were introduced:
1. Paras. 2.2.6.2.2 and 2.2.6.2.3 enables the provision of temperature and dew-point temperature in METAR and SPECI to be in tenths of a degree Celsius as well as in steps of tenths of a degree Celsius:
<p align="center"><img src="https://github.com/wmo-im/iwxxm/assets/30064374/200a9aee-e6d9-4008-9fb6-7c3a5f3c296c)" width="600"></p>
2. Para. 2.2.3.6.5 enables the provision of all runways in METAR and SPECI if there is a necessity to include RVR values:
<p><p align="center"><img src="https://github.com/wmo-im/iwxxm/assets/30064374/57c9917d-883b-44f7-b195-52a3cf3b2472" width="600"></p>

### Amendment details

As described in the [following post](https://github.com/wmo-im/iwxxm/issues/309#issuecomment-1732836511).

### Requestor(s)

METP / Amendment 81

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.3, METAR and SPECI

**Comment by blchoy** [comment]
**Summary of changes made**

1. **Provision of temperature and dew-point temperature in METAR and SPECI to be in tenths of a degree Celsius as well as in steps of tenths of a degree Celsius**:
   * No change to the schema is required.  The notes were updated accordingly.
2. **Provision of RVR values of all runways in METAR and SPECI as necessary**:
   * The multiplicity of iwxxm:rvr has been revised to [0..*].

**Comment by blchoy** [comment]
Included in IWXXM 2025-2RC1.
