### ISSUE TITLE
Post a ZIP file of version 2021-2

### ISSUE THREAD

**Issue by amilan17** [wmo-im/iwxxm#310]
### Details

 
https://schemas.wmo.int/iwxxm/2021-2/

### Requestor

Anna Milan (WMO), @amilan17

**Comment by amilan17** [comment]
@blchoy Can you check to see if this is what's expected? 
https://schemas.wmo.int/iwxxm/2023-1RC1/

**Comment by blchoy** [comment]
> @blchoy Can you check to see if this is what's expected? https://schemas.wmo.int/iwxxm/2023-1RC1/

Checked OK.  Thank you.
