### ISSUE TITLE
WIP: IWXXM Quantitative Volcanic Ash Product

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#315]
For your consideration I have enclosed the following items in the attached zip file so that you may be able to review the first draft of the QVA UML model and its XML schema.

From the schema and the example that the ICAO Working Group provides in the Word document, a QVA XML document was created. There are additional follow-up questions for the team and, if still unresolved, the ICAO working group to consider.

The items in the zip file are as follows:

1) From the ICAO Working Group, a Word document detailing the QVA product requirements: IWXXM QVA Schema Requirements.docx.

2) From those requirements, a UML model for the QVA product was created. This model leverages the tremendous work done by Choy for the WAFS Significant Weather product. The EA project file, icao-iwxxm-qva.eap, and corresponding diagram image file, QVA-UML-Diagram.png are provided. (I do not know if all TT-AvData members have Enterprise Architect, hence the PNG file.)

3) From EA and the UML model for QVA, the IWXXM QVA schema file is generated. I kindly request that you review qva.xsd for any errors or omissions. (The other supporting XSD files, common.xsd, measures.xsd and metFeatures.xsd are essentially unchanged from the 2021-2 release.)

4) Using the example of the ash cloud depiction/scenario in the Word Document (item 1), I've recreated these clouds in Google Earth. The KML file is provided if you have Google Earth on your computer or can use https://earth.google.com  This extra step was done to provide semi-realistic latitude/longitude information in the subsequent XML document.

5) Based on the schema, an incomplete but still relatively realistic XML document was produced, Example_QVA.xml.

If you want to examine the XML files in OxygenXML application (or similar) change the schema location information in Example_QVA.xml to the correct path to the IWXXM QVA schema file on your computer, i.e. replace "C:/Users/Mark.oberfield/Desktop" with your path.  The QVA schema and XML document validates.  As of yet, there are no QVA specific schematron rules.

While building out the XML example, I had some questions regarding incomplete 24-hr forecasts and how that might be depicted in the document.

Please let me know if you have any difficulties with the files.
[QVA.zip](https://github.com/wmo-im/iwxxm-modelling/files/7738608/QVA.zip)

**Comment by blchoy** [comment]
After some time, I finally find some time to finalize the QVACI package.  The following are my initial response to Mark's suggestions:

[QVACI-rev.zip](https://github.com/wmo-im/iwxxm/files/12519569/QVACI-rev.zip)

**Comment by Deterville** [comment]
> For your consideration I have enclosed the following items in the attached zip file so that you may be able to review the first draft of the QVA UML model and its XML schema.
> 
> From the schema and the example that the ICAO Working Group provides in the Word document, a QVA XML document was created. There are additional follow-up questions for the team and, if still unresolved, the ICAO working group to consider.
> 
> The items in the zip file are as follows:
> 
> 1. From the ICAO Working Group, a Word document detailing the QVA product requirements: IWXXM QVA Schema Requirements.docx.
> 2. From those requirements, a UML model for the QVA product was created. This model leverages the tremendous work done by Choy for the WAFS Significant Weather product. The EA project file, icao-iwxxm-qva.eap, and corresponding diagram image file, QVA-UML-Diagram.png are provided. (I do not know if all TT-AvData members have Enterprise Architect, hence the PNG file.)
> 3. From EA and the UML model for QVA, the IWXXM QVA schema file is generated. I kindly request that you review qva.xsd for any errors or omissions. (The other supporting XSD files, common.xsd, measures.xsd and metFeatures.xsd are essentially unchanged from the 2021-2 release.)
> 4. Using the example of the ash cloud depiction/scenario in the Word Document (item 1), I've recreated these clouds in Google Earth. The KML file is provided if you have Google Earth on your computer or can use https://earth.google.com  This extra step was done to provide semi-realistic latitude/longitude information in the subsequent XML document.
> 5. Based on the schema, an incomplete but still relatively realistic XML document was produced, Example_QVA.xml.
> 
> If you want to examine the XML files in OxygenXML application (or similar) change the schema location information in Example_QVA.xml to the correct path to the IWXXM QVA schema file on your computer, i.e. replace "C:/Users/Mark.oberfield/Desktop" with your path. The QVA schema and XML document validates. As of yet, there are no QVA specific schematron rules.
> 
> While building out the XML example, I had some questions regarding incomplete 24-hr forecasts and how that might be depicted in the document.
> 
> Please let me know if you have any difficulties with the files. [QVA.zip](https://github.com/wmo-im/iwxxm-modelling/files/7738608/QVA.zip)

Thank you for update.  24 hr. incomplete TBD noted.
