### ISSUE TITLE
Metar - element "State of Runway" should not exist anymore.

### ISSUE THREAD

**Issue by Mattonius5** [wmo-im/iwxxm#324]
**Affected version:**
 - 2023-1

**Expected behaviour**
Version 2023-1 is well past the due date of the element removal; As such, it shall not be an acceptable element within the schema.
Any IWXXM Metar with version 2023-1 containing "State of runway" element(s) shall cause an XSD validation error.
Furthermore, files "metar-EDDF-runwaystate.tac" and "metar-EDDF-runwaystate.xml" should be removed from the examples.

**Additional context**
IWXXM 2021-2 and IWXXM 2023-1 shall comply with Amendment 80 to Annex3.
_"Until November 4th 2021, the Runway State Group (RSG) in a METAR could be used as an alternative to the SNOWTAM. As of November 5th 2020, it is to be only disseminated by a NOTAM."_
Amendment 80 to Annex3 (4.8.1.5 b) states that Element(s) "State of Runway" was to be effectively removed from METAR as of November 4th 2021
Because IWXXM 2021-2 was issued before November 4th 2021, I would understand the element being present for a transition period, but I wonder if action should be taken to this schema version.

[Annex 3 - Amendment 80 - Metar & Speci.pdf](https://github.com/wmo-im/iwxxm/files/12342188/Annex.3.-.Amendment.80.-.Metar.Speci.pdf)

**Comment by blchoy** [comment]
Thank you for pointing this out.  Yes we are well aware of the enforcement of this requirement.  We will be removing this in the upcoming version to be released in 2024 which intends to support Amendment 81 to ICAO Annex 3.

**Comment by blchoy** [comment]
This is now handled under #325 and this issue is therefore closed.
