### ISSUE TITLE
Add Schematron rules to mandate the use of UUIDs

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#33]
As discussed in TT-AvXML-6, it was agreed that we will use UUIDs for all gml:ids.  Add Schematron rules to enforce this.

**Comment by braeckel** [comment]
This change will break backwards compatibility with nearly every IWXXM generator library that exists today, almost none use UUIDv4 for gml:ids.  This change should be considered in light of this major breakage as evaluated against the benefit of not having to worry about duplicate gml:ids in COLLECT collections.  AIXM precedent on this topic should be investigated.

**Comment by braeckel** [comment]
Whether Schematron rules are required for UUIDs or not boils down to the question of whether it is acceptable for IWXXM messages to be modified en route when moved in and out of COLLECT containers and whether aggregators (for example ROCs) should be required to be able to perform these modifications to IWXXM messages.  If UUIDs are not mandated on messages States are in the unfortunate position that the content they issue may not be the content that is received by end users - ids may be modified en route.  This may create challenges around being able to identify and track reports back to the State that issued them.  For these reasons, while UUID Schematron rules will require software modifications by States they are necessary for keeping messages unchanged during distribution with AMHS/COLLECT and will also be necessary for similar reasons for future WFS (MET-SWIM) exchanges.

**Comment by blchoy** [comment]
This is to remind ourselves that the proposed COMMON.Report5 rule should be added as a constraint of the UML Class Report.

**Comment by blchoy** [comment]
We still need to add COMMON.Report5 to the UML model.

**Comment by braeckel** [comment]
COMMON.Report5 has been added to the UML and checked in
