### ISSUE TITLE
Missing <quantity> tag defining quantity-kind (e.g. heightAtTopOfCloud) in the schemas

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#34]
related to #20 

is
http://codes.wmo.int/common/c-15/me/heightOfTopOfCloud 

explicitly part of IWXXM 2.1?

Is this:
* in the UML
* in the schema
* in WMO No. 306 Vol I.3 Common Code-table D-2 (errata may be required)

is there a bug in the export

**Comment by blchoy** [comment]
There is indeed a sequence "0 20 014" describing "Height of top of cloud" in BUFR Table B/20:

![image](https://user-images.githubusercontent.com/30064374/32667502-db4c975c-c675-11e7-99d0-d7f604439f8a.png)

This is being referenced in iwxxm:AIRMETEvolvingCondition/@cloudTop which is analogous to that referenced in iwxxm:AIRMETEvolvingCondition/@cloudBase.

**Comment by braeckel** [comment]
The question would be why it is present in UML but not in the resulting XML schema.  Overall this appears to be a code entry that should be retained, and we should track down the UML -> XML schema translation issue.

After digging in further it appears that the only XSD reference to cloud types in http://codes.wmo.int/common/quantity-kind/ is coming from common.xsd on CloudLayerType/base.  Neither AIRMET nor SIGMETEvovingCondition (both of which have cloudBase and cloudTop) are carrying the quantity metadata properly out to XSD.  One difference may be that CloudLayerType/base references the DistanceWithNilReason whereas *EvolvingCondition/cloudTop and cloudBase references a Distance.

**Comment by blchoy** [comment]
I see.  You are not only referring to the missing item in the code registry but the missing <quantity> in the schema.  The latter is related to the fact that the EA serialization adaptation in accordance to our request some years ago did not cover the case where the tagged value is associated with an UML class attribute.  This is, however, not too difficult to handle in our post-processing XSLT and I will see if I can fix this over the weekend.

**Comment by blchoy** [comment]
I have completed updating the style sheets used to generate the schemas and AIRMET.xsd should now have the necessary quantity tags and information.  AIRMET.xsd and Release Notes have updated accordingly.

**Comment by marqh** [comment]
http://codes.wmo.int/common/quantity-kind/heightAtTopOfCloud is required

**Comment by blchoy** [comment]
As the item in the code registry will be followed in #20, I am closing this ticket to simplify tracking.
