### ISSUE TITLE
Add a WMO Codes redirect from 49-2/observation-types/iwwxm to 49-2/observation-types/IWXXM

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#35]
As discussed in TT-AvXML-6 the observation-types register is in IWXXM as http://codes.wmo.int/49-2/observation-type/iwxxm but the only entry is http://codes.wmo.int/49-2/observation-type/IWXXM.  

The solution identified was to set up a redirect from http://codes.wmo.int/49-2/observation-type/iwxxm to http://codes.wmo.int/49-2/observation-type/IWXXM.

**Comment by marqh** [comment]
following 8th November meeting, the decision is to reverse the implementation

iwxxm will redirect to IWXXM

**Comment by marqh** [comment]
http://codes.wmo.int/49-2/observation-type/iwxxm is now a redirect to http://codes.wmo.int/49-2/observation-type/IWXXM
