### ISSUE TITLE
Create new (more readable) WMO Codes tables for current bufr4 references

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#37]
ICAO Annex 3 and IWXXM 2.x reference codes like http://codes.wmo.int/bufr4/codeflag/0-20-008/3 for "BKN".  The current bufr4 code tables have several issues:

- the URLs are opaque and there is no easy indication that 0-20-008/3 is equivalent to "BKN"
- the code lists in BUFR include more options (in some cases) than are allowed in ICAO Annex 3

New code list entries should be considered (perhaps under an "ae" register) for all bufr4 code list references in the schemas.

**Comment by blchoy** [comment]
This is related to #175 in which two code tables has changed to 49-2 publication.  But there are still BUFR tables being referred to, including 0 20 86 (runway deposits), 0 20 87 (runway contamination), and 0 22 61 (state of the sea).  This issue will remain open until these tables have changed to 49-2 publication and there is a decision on whether we will deprecated the OPMET BUFR sequences and tables which have never been used.

**Comment by blchoy** [comment]
As AerodromeRunwayState will retire (ditto the corresponding code lists) in Amendment 79, we may want to take this opportunity to also incorporate the code table for SeaSurfaceState into WMO No.306 and control from there.

**Comment by blchoy** [comment]
This should have been done in IWXXM 3.0 and is hereby closed.
