### ISSUE TITLE
Feedback for wmdr developers - COLLECT cannot handle collections of wmdr records

### ISSUE THREAD

**Issue by sforeman** [wmo-im/iwxxm#40]
Developers working on  the wmdr (representation of WIGOS metadata) found that COLLECT did not meet their needs for gathering several wmdr documents into a single container.

It is desirable to avoid multiple types of container, and thus modifications of COLLECT to address the problems identified by the wmdr developers are advisable.

**Comment by blchoy** [comment]
This issue has moved to wmo-im/collect#1
