### ISSUE TITLE
Add SIGWX representations to IWXXM

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#42]
As directed by the ICAO METP, add SIGWX representations to IWXXM

**Comment by braeckel** [comment]
Two-way transformation to existing BUFR representations is important for the WAFCs

**Comment by braeckel** [comment]
It was agreed in TT-AvXML-6 that the WMO Codes Registry structure for sigwx phenomena should be an Annex 3-specific list (ICAO) that points to the "master", larger list of sigwx phenomena owned by WMO.  This is to allow flexibility in expanding the ICAO list which points to entries in the WMO list as Annex 3 requirements change in the future.

**Comment by blchoy** [comment]
Interesting to know that it is supposed to be introduced in Amd 79:

_**Action MIE/3-06: IWXXM SARPs for SIGWX**
That the WG-MIE develop draft IWXXM standards and recommended practices (SARPs) for Annex 3 Amendment 79 for SIGWX, for consideration by the METP._

Need to differentiate this schema from the rest which are there in accordance to the SARPs.

**Comment by braeckel** [comment]
This issue should be moved to a later version of IWXXM since it is targeted on Amd 79

**Comment by braeckel** [comment]
In MIE/4 it was requested that a SigWx schema be developed by Nov of 2020 at the latest, and ideally as soon as possible.  This has been added back to IWXXM 3.1.

**Comment by braeckel** [comment]
It is suggested that the first versions be shared with the WAFCs for feedback before publication

**Comment by braeckel** [comment]
This representation was discussed in MIE/4 together with GAMET and low level SIGWX.  The decision in MIE/4 was for TT-AvXML to develop a general-purpose representation that could carry geographic area, heights, and phenomena in a single representation for all of these "products".  MIE will continue to discuss, including such aspects as what we would call this general-purpose area hazard thing.

**Comment by blchoy** [comment]
This is being taken care in https://github.com/wmo-im/iwxxm/issues/219 and is hereby closed.
