### ISSUE TITLE
Assess the use of intersecting geometries as a way of describing AIR/SIGMET areas

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#43]
In TT-AvXML-6 the possibility of expressing SIGMET (and AIRMET) phenomena as an intersection of geometries was discussed.  WG-MIE-4 asked TT-AvXML to consider this alternative.  In discussion it became clear that this has impacts on forecasters and the AIR/SIGMET production process that is well outside the scope of TT-AvXML.  

This task is to assess the feasibility and challenges of using the intersection of AIR/SIGMET phenomena (such as a TC circle) with FIR boundaries explicitly.

Discussed challenges include:

 - Consumers need to do their own intersection to find the actual area of impact rather than having an explicit geometry with the met condition in the relevant FIR
 - Nearby FIRs with the same phenomena may describe a different region for the same phenomena.  While each FIR has primary responsibility for its region the different forecasts may end up being inappropriately used by consumers

**Comment by braeckel** [comment]
This was taken up by MIE in MIE/4 and TT-AvXML can respond when a policy decision is made on this issue.  TT-AvXML can implement this option when so directed by MIE, so this is hereby moved out of 3.0RC1

**Comment by blchoy** [comment]
To supplement Aaron's comment, in designing representation in XML, we will have to consider whether the resulting instance is easier to be prepared by the producer or to be consumed by the end user.  Consensus up to this moment is to favour consumption.  Agreed that there is no immediate urgency to have this implemented in IWXXM 3.0.
