### ISSUE TITLE
Add optional report ids for referencing cancellable, correctable, amendable, etc report types

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#46]
There are currently loose practices around having unique sequence ids with SIGMETs in particular.  For backwards compatibility IWXXM should retain the sequence number method as a mandatory mechanism, and as an improvement should be able to cancel/amend/correct by id.  In the case of conflict the sequence number should take precedence, which should be documented in the schemas.

This is a conclusion after discussion of #18 .

**Comment by braeckel** [comment]
Note that this is contingent upon having unique ids via UUID, relating to issue #31

**Comment by braeckel** [comment]
This capability should apply to all referential messages such as cancellations, corrections, amendments, etc.

**Comment by blchoy** [comment]
I think we will also need to review how we are using the bulletinzed version of TAC reports in our daily operation and back port certain essential features into IWXXM to reduce its dependence on COLLECT to provide these features.  This is to prepare for future use of other transport/collection mechanisms with IWXXM.

**Comment by braeckel** [comment]
This may not fit into IWXXM 3.0RC1 given the timeline and consideration required.  I suggest that this be moved to a later version of IWXXM

**Comment by braeckel** [comment]
This should be implemented as a "targetReportId", "referencedReportId", "priorReportId" or something similar.  An additional Schematron rule can enforce that these are UUID references.  

TT-AvXML/7 considered the use of AHL to reference from bulletin to other bulletin and determined that there is no need for such id references in COLLECT.

**Comment by blchoy** [comment]
This is also related to #172.

**Comment by blchoy** [comment]
As time progresses the motivation to further improve the legacy IWXXM reports has decreased.  In particular, with the introduction of WxObject and the mandatory use of gml:identifier to identify an iwxxm:MeteorologicalFeature or iwxxm:MeteorologicalFeatureCollection, it is possible to implement cancellation, correction, amendment to these objects depending on particular use cases.  I consider this issue has completed it mission and is hereby closed.
