### ISSUE TITLE
Projection used to prepare VAA, SIGMET and AIRMET messages

### ISSUE THREAD

**Issue by blchoy** [wmo-im/iwxxm#52]
In Annex 3, there are notes to the _Advisory message for Volcanic Ash_ and _SIGMET/AIRMET_ which indicate that a line inferred in the message by the joining two points is "a straight line between two points drawn on a map in the Mercator projection or a straight line between two points which crosses lines of longitude at a constant angle".

At ICAO METP MOG2 in 2016, a working paper (SN/16) _Map Projections used for Displaying Volcanic Ash Forecasts: Update of Model VAG and Model SVA of Appendix I to Annex 3_ had specifically pointed out the discrepancies of straight lines prepared on the Mercator projection and displayed on other projections.   The paper further mentioned that "the group may note that the transition to IWXXM and its use of XML/GML geospatial conventions should permit greater flexibility in originating and visualizing such phenomenon since information regarding the projection on which the polygons were generated can be included".

However, in the IWXXM examples for VAA, SIGMET and AIRMET, aixm:horizontalProjection of aixm:AirspaceVolume is either not included or specified incorrectly as http://www.opengis.net/def/crs/EPSG/0/4326.  The correct projection should be http://www.opengis.net/def/crs/EPSG/0/3395.

It is thus necessary to:
1. Amend the examples as necessary
2. Consider mandating the use of aixm:horizontalProjection to describe projection of the geospatial object with schematron rule(s) in IWXXM 3

**Comment by braeckel** [comment]
Given the ongoing discussion on this topic and approaching deadline I suggest that this be moved from IWXXM 2.1.1 to IWXXM 3.  With @blchoy concurrence we can move this issue.

**Comment by blchoy** [comment]
No objection at all.

**Comment by braeckel** [comment]
This is a duplicate issue (a more restrictive case) of #44.  Some key background from this issue was put into #44 and this issue is closed
