### ISSUE TITLE
How to Represent SIGMET based on Pilot Report (Single lat/lon coordinate)

### ISSUE THREAD

**Issue by jkorosi** [wmo-im/iwxxm#55]
We believe the schema documentation and/or examples should say how to cover
this case. The problem is that aixm:AirspaceVolume’s horizontalProjection
contains aixm:Surface, which extends gml:SurfaceType. A surface can not be a
simple point, it has to be some 2D surface.
Luke Dunstan in the above thread suggested using gml:CircleByCenterPoint
with zero radius. If you agree, then please document that in the schema and
examples because otherwise IWXXM implementors will each choose a different
way how to handle this single point case.

This stems from cbs-tt-avxml:

- [CBS TT-AvXML - IWXXM 2.0 SIGMET/AIRMET: Can single point hazard locations be represented](https://groups.google.com/a/wmo.int/forum/#!searchin/cbs-tt-avxml/IWXXM$202.0$20SIGMET$2FAIRMET$3A$20Can$20single$20point$20hazard$20locations$20be$20represented$3F/cbs-tt-avxml/cjKNzG4gPAg/MVomguJcBQAJ)?

**Comment by blchoy** [comment]
Sounds sensible to me.

**Comment by jkorosi** [comment]
Real world examples of point location SIGMET:
WSNZ21 NZKL 012125
NZZC SIGMET 21 VALID 012134/020134 NZKL-
NZZC NEW ZEALAND FIR SEV TURB OBS AT 2123Z S4123 E17315 FL045 STNR NC=

WSUR31 UKBV 280728
UKBV SIGMET 3 VALID 280730/280830 UKBV-
UKBV KYIV FIR/UIR SEV TURB OBS N4930 E03050 FL370 MOV E 30KMH NC=

There are two possible valid examples how can be point based SIGMET reported in attachment. One represents point by <gml:CircleByCenterPoint/> and another by <gml:posList/>.

[examples.zip](https://github.com/wmo-im/iwxxm/files/1414135/examples.zip)

**Comment by braeckel** [comment]
It was agreed in today's telecon that we should update TAC-to-XML-Guidance.txt and put this into the iwxxm-translation set of examples.

**Comment by braeckel** [comment]
The CircleByCenterPoint example (originally sigmet-point-as-gml-CircleByCenterPoint.xml, now named sigmet-point.xml) has been checked into the iwxxm-translation repo as https://github.com/wmo-im/iwxxm-translation/commit/05ddcdc16a47a6484d8f45c2e21c58840fa0eaa1 with minor modifications.
