### ISSUE TITLE
The validation of collection doesn't respect XSD definition

### ISSUE THREAD

**Issue by jkorosi** [wmo-im/iwxxm#58]
If a collection is created by older version 1.1 instead of version 1.2 which is required by [iwxxm-collect.xsd](http://schemas.wmo.int/iwxxm/2.1.0/iwxxm-collect.xsd) then the validation doesn't failed and the collection is marked as a valid (tested by http://wmo-icao-validator.rap.ucar.edu/).
If we done the validation just against to XSD schema then this error is detected (at least in our XSD validation process).
I am not sure if it is an error or some configuration issue of Crux validator. If it cannot by fixed then 
maybe some additional Schematron rule should be defined in [iwxxm-collect.sch](http://schemas.wmo.int/iwxxm/2.1.1/rule/iwxxm-collect.sch) to secure using of correct collection version.
It doesn't seem to be so big issue but the order of **meteorologicalInformation** and **bulletinIdentifier** elements is reverted in definition of **MeteorologicalBulletinType** sequence type between these two versions, so the structure of produced bulletin depends on the used collect schema version.

The examples created in both versions are attached in [collect.zip](https://github.com/wmo-im/iwxxm/files/1479739/collect.zip) file.

**Comment by braeckel** [comment]
This is an issue with the online validator tool, and is likely due to how the online validator tool chooses and validates against the collect schema independently of the IWXXM version.

**Comment by blchoy** [comment]
As the online validation tool has been retired, this issue is superseded by event and is hereby closed.
