### ISSUE TITLE
Identify which nilReason is most appropriate for WMO Code Table 1079 option 99

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#6]
An appropriate nilReason should be identified (either from the OGC set or from the WMO Codes Registry) for METAR depthOfDeposit in runway state:
"Runway or runways non-operational due to snow, slush, ice, large drifts or runway clearance, but depth not reported"

This is taken from WMO Code Table 1079 value 99.

ref: https://software.ecmwf.int/issues/browse/AVXML-10

Created:
    29/Sep/15 7:57 PM 

Reporter:
Aaron Braeckel

**Comment by marqh** [comment]
David Hunter added a comment - 02/Oct/15 1:46 PM

Comments from Jeremy Tandy:
Class AerodromeRunwayState indicates that attribute depthOfDeposit is optional- so doesn’t strictly need a nil-reason … e.g. when attribute snowClosure = `true`.

That said, existing options for nil reason include:
• Inapplicable (it’s closed, we didn’t measure) http://www.opengis.net/def/nil/OGC/0/inapplicable
• Missing (the value is not reported- but I’m not telling you why) http://www.opengis.net/def/nil/OGC/0/missing
• Unknown (it’s closed, we didn’t measure) http://www.opengis.net/def/nil/OGC/0/unknown

See http://codes.wmo.int/common/nil for more details.

The last of these is you best option.

However, if a more specific reason needs to be added, we can amend the nil-reason list … e.g. something like “notMeasured” – the value is not reported due to operating conditions?

TT-AvXML would need to propose an amendment. Then it goes thought the fast-track process.


Permalink Edit
aaron.braeckel Aaron Braeckel added a comment - 02/Oct/15 6:15 PM

To be clear, this is a change related to AvXML-9. The issue is that there are two different conditions on depthOfDeposit that need to be represented:

// - depth of deposit operationally not significant or not measurable
99 - Runway or runways non-operational due to snow, slush, ice, large drifts or runway clearance, but depth not reported

I raised this as a separate issue because these are fairly specific conditions that do not cleanly match with the existing nilReasons. We can find the closest nilReason for these cases but note how "//" can mean one of two different things, each of which could be represented by an appropriate (existing) nilReason. Additionally, in some cases the WMO Codes Registry has included register items such as http://codes.wmo.int/bufr4/codeflag/0-20-089/127 which represents the BUFR code table entry for a similar type of case. We then reference these BUFR entries as the nilReason in some cases. The original BUFR code table 1079 has two entries for "//" and "99" which are not currently present in the WMO Codes Registry. Code table 1079 is a complicated case for representation in the Codes Registry because it mixes quantities (values 0-90) and categorical values (90-99 and //).

It is probably best to do the following:
// - depth of deposit operationally not significant or not measurable: missing element ("not reported")
99 - Runway or runways non-operational due to snow, slush, ice, large drifts or runway clearance, but depth not reported: missing element with snowClosure=true

This is not completely consistent with other parts of the model which don't have the equivalent of a snowClosure=true business rule, but this does not seem like a critical and urgent problem.

**Comment by braeckel** [comment]
It was agreed in TT-AvXML-6 that Code Table 1079 would be put into the WMO Codes Registry under codes.wmo.int/49-2/.  depthOfDeposit would then be able to reference entry 99 as the nilReason.  

This should also be documented in the TAC to XML guidance document.

**Comment by blchoy** [comment]
A nilReason http://codes.wmo.int/common/nil/unknown will be used for the case of "99" and the corresponding part in TAC-to-XML-Guidance.txt has been modified.
