### ISSUE TITLE
Combine iwxxm.sch, iwxxm-collect.sch and rules for offline checking of WMO Code Registry contents

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#60]
There are only minor differences between iwxxm.sch and iwxxm-collect.sch, essentially only a single COLLECT rule.  This rule (COLLECT.MB1) only takes action when a COLLECT element is used, which means that iwxxm-collect.sch is a drop-in replacement for iwxxm.sch.  Combine all Schematron files into a single iwxxm.sch file, which may be as simple as renaming iwxxm-collect.sch to iwxxm.sch.

**Comment by blchoy** [comment]
Ditto for the rules for offline checking of WMO Code Registry items mentioned in #30.

**Comment by blchoy** [comment]
While the extraction of tables from the registry has to be done separately, the inclusion of code list checking rules in the schematron file could be incorporated into the existing XSLT used to generate the schematron file.  There is also a possibility to extend the checking to cover other places where code list entries are being used (e.g. nilReasons).

**Comment by blchoy** [comment]
The XSLT scripts used to create SCH files directly from XMI file were committed to the SVN.

**Comment by blchoy** [comment]
The current rule ids I am using in the schematron file generation XSLT is: ALLCAPS("UML Classname")."XPath with '/' replaced by '.'".  For example: "VolcanicAshAdvisory.VolcanicAshAdvisory.colourCode"

This, however, is slightly different from existing ids for manual rules as sometimes we are using abbreviations to the UML Classname.  An example is: "VAA.VAA2"

Suggestions are most welcome.
