### ISSUE TITLE
Provide guidance on the use of COLLECT in bulletinizing IWXXM messages

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#66]
Document guidance on the use of COLLECT with IWXXM messages.  The goal would be that IWXXM messages not change during the COLLECT/de-COLLECT process so they can be identified downstream.

A few example principles:
 - namespaces should not move
 - IWXXM messages are not modified at all when bulletinizing/debulletinizing
 - COLLECT should not define namespaces, other than the COLLECT namespace
 - The top-level/root ID (for example the METAR id) is used for unique identification

**Comment by blchoy** [comment]
When we are doing some IWXXM creation and exchange tests with neigbouring centres, we notice that during aggregation, we may come across cases when IWXXM messages are coded in different versions.  In that case, we have no choice but to alter the definition of name space of IWXXM of some of these messages from the default xmlns:iwxxm to xmlns:iwxxm1 to discriminate the simultaneous occurrence of IWXXM messages of different version within a single COLLECT aggregation.

Any suggestions on how to keep IWXXM messages from the need to modify is most welcome.

**Comment by braeckel** [comment]
Also, document if a particular version of COLLECT is required for each version of IWXXM, or whether any version of COLLECT can be used.

**Comment by blchoy** [comment]
I suggest to change the associated milestone from IWXXM 3.0rc1 to IWXXM 3.0 as there is no need to have it ready together with the release candidate.

**Comment by braeckel** [comment]
This is now a sub-task of #82 and is being closed
