### ISSUE TITLE
Create an IWXXM 3 Transition Guide

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#70]
Consider creating a transition guide for IWXXM software developers and in particular data producers to help describe how to move from IWXXM 2 to IWXXM 3.

**Comment by blchoy** [comment]
I prefer making this as simple as possible as WMO No.306 Vol I.3 is already very complicated.  A table highlighting the differences between IWXXM 2 and 3 as a section of WMO No.306 should be intuitive enough to (i) assist developers implement the changes and (ii) help managers understand the scale of work involved.

**Comment by braeckel** [comment]
This issue is closed as it is part of the wiki update process.  WMO 306 includes the codes/content as-is and does not discuss the transition process.
