### ISSUE TITLE
TEST and EXERCISE TC/VA ADVISORY

### ISSUE THREAD

**Issue by jkorosi** [wmo-im/iwxxm#71]
There is a requirement **Action MIE/3-04: Partially Translated Messages (refer Activity 4.8)** in [TT-AvXML-6-d05.02-MIE3_Report_Final_V1](https://wiswiki.wmo.int/tiki-download_item_attachment.php?page=TT-AvXML-6&attId=260)
>That, given that the agreed minimum set of information to be present to allow a translation (refer SN10) is:
METAR: METAR (COR) CCCC YYGGggZ TAF: TAF (COR/AMD) CCCC YYGGggZ
SIGMET/AIRMET: CCCC SIGMET | AIRMET ... VALID YYGGgg/YYGGgg
VAA: DTG, VAAC TCA: DTG, TCAC
where " | " indicates a logical "OR", "( group )" indicates an optional group
that the WG-MIE request that WMO can provide an IWXXM schema version allowing the use of particular dedicated tags with the indication of NIL, even for Annex 3 mandatory MET elements, and indication of the incoming TAC with specific tags when translation fails.

The Amendment 78 introduces **TEST or EXERCISE indicator** for warning reports.
For VA ADVISORY it is:
![image](https://user-images.githubusercontent.com/29196082/35113590-3e4aba4a-fc82-11e7-9abf-e55d00323d24.png)
So my understanding is that you can create a test/exercise report as
`VA ADVISORY TEST`
where DTG and VAAC groups may be missing due to note below the table.

I think the **TEST or EXERCISE indicator** should be moved after **Name of VAAC** to handle **Action MIE/3-04: Partially Translated Messages (refer Activity 4.8)** requirement.
The same should be done also for TC ADVISORY.

For SIGMET and AIRMET reports TEST or EXERCISE follow after all necessary information, so no action is needed.
![image](https://user-images.githubusercontent.com/29196082/35114169-24286444-fc84-11e7-8d01-49172a4a7f54.png)

**Comment by jkorosi** [comment]
Should be linked to #41.

**Comment by braeckel** [comment]
This is not an IWXXM issue but is instead an issue with Annex 3 templates.  This was however addressed in Amendment 78.  For both reasons this issue can be closed
