### ISSUE TITLE
TC ADVISORY changes in Amendment 78

### ISSUE THREAD

**Issue by jkorosi** [wmo-im/iwxxm#72]
There are following changes:

* Advisory number: the type of advisory number is an integer but it should be change into string as it is for VA ADVISORY
* Observed position of the centre - the time of observation is added
* Observed CB cloud - observed cloud is added
* Also the **Remarks** and **Expected time of issuance of next advisory** are mandatory, so the min occurrence of **remarks** and **expectedNextAdvisoryTime** should be changed from  to 1. The same should be done for VA ADVISORY
![image](https://user-images.githubusercontent.com/29196082/35115449-80c530b6-fc88-11e7-91bb-cf1b8351ff4e.png)

**Comment by braeckel** [comment]
This issue is already covered by #49 and will be closed
