### ISSUE TITLE
Change AIXM schema locations to stable URLs

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#73]
IWXXM is currently using unstable URLs for our schema references to AIXM schemas on the aixm.aero site.

There are several aspects to this fix:
 - Schema updates, covering all versions of IWXXM
 - schemas.wmo.int updates with the new versions of the schemas
 - Notifying IWXXM users/developers of the change and providing a public indication of which schemaLocations are correct

AIXM developers indicated that the following URLs should be used and will remain stable:
 - http://www.aixm.aero/schema/5.1.1_profiles/AIXM_WX/5.1.1a/AIXM_Features.xsd (for AIXM 5.1.1)
 - http://www.aixm.aero/schema/5.1_profiles/AIXM_WX/5.1.a/AIXM_Features.xsd  (for AIXM 5.1)

IWXXM is using a profile of AIXM and should use the URLs above, but for completeness the following URLs are available for referencing the **full**, non-profiled AIXM schemas:
 - http://www.aixm.aero/schema/5.1.1/AIXM_Features.xsd
 - http://www.aixm.aero/schema/5.1/AIXM_Features.xsd

For making changes to IWXXM schemas there are a few alternatives:
 - Silently change schemaLocations without any version changes.  There would be two variants of IWXXM 2.0.0, 2.1.0, 1.1RC1, etc. with different schemaLocations for the AIXM schemas - one previously released and one updated with new locations now.  This is the easier option and given that the only changes are in a single schemaLocation it may be feasible, but the dual schema variations for each IWXXM version are a concern
 - Change the schemas and increment a patch version number (3.0.0 -> 3.0.1, for example).  This would be required for every version of IWXXM that is publicly available.  It may be possible to leave much of the existing versions, directory names, and namespaces the same but change the version="3.0.0" in the schemas to version="3.0.1" (for example)

The WMO process and approval differences between each approach are unclear.

**Comment by blchoy** [comment]
The (aviation) weather community has a strange habit to store OPMET in its original transmission form.  For TACs decades ago all they need is to pull out the old Annex 3 and GTS manual on their bookshelves and they should have no problem decoding.  For IWXXM the situation is a bit different as we cannot guarantee all schemas we used to reference will be available online even until IWXXM has become obsoleted.

If we treat the use of the previous locations a mistake then it may worth correcting them with methods mentioned by Aaron.  However, if one think the obsoleted IWXXM schemas is a moment of history then it may not necessarily need the changes.  Imagine decades later if the schema owner change the location of their historic schemas again, shall we move on to change IWXXM 1.1?

A long term approach could be the storing of referenced schemas on schemas.wmo.int for each version of IWXXM.

**Comment by sforeman** [comment]
We should amend iwxxm 2.1.1 to refer to the long-term stable locations on aixm.aero. This should be done before the formal release of iwxxm 2.1.1 as an editorial change following the fast track consultation.

**Comment by braeckel** [comment]
Per our discussion earlier this week it was agreed that prior versions of IWXXM will not be modified as they are working now and unlikely to break in their lifetimes and that schema locations are straightforward to address in archival scenarios with existing XML technology like XML catalogs.  Therefore the stable AIXM schema locations will only be made to new versions (in 3.x).  The challenges of updating older schema versions are quite significant, not the least of which are the WMO procedural requirements.

Just a reminder that in addition to 3.x schema and example changes we need to notify the email list of the background and reason for this change.

**Comment by braeckel** [comment]
After searching through it doesn't appear that there are any unstable URLs in use in 3.0RC1, the only cases where they remain are in 2.0RC1 examples and in catalog locations which map the unstable URLs to local schema paths.  Therefore 3.0RC1 is referencing only the stable URLs as of now and no changes are needed.

**Comment by blchoy** [comment]
I don't think we want to alter published versions.  As the unstable URLs are not being found in 2.1.1RC1/2.1.1 and 3.0RC1 examples can we close this issue?
