### ISSUE TITLE
Missing "recent weather" code from METAR (and hence iwxxm)

### ISSUE THREAD

**Issue by sforeman** [wmo-im/iwxxm#74]
While editing the text of Annex 3 to accommodate the expected amendments in Amd 78, ICAO has discovered that the recent weather term "RERASN" was accidentally removed in an earlier amendment to the document. ICAO is re-instating the missing term as an editorial change.

The iwxxm code table http://codes.wmo.int/49-2/AerodromeRecentWeather is intended to be consistent with the requirements of Annex 3, so the term RERASN should also be added to that table.

**Comment by braeckel** [comment]
This code register is now publicly available and this issue can be closed
