### ISSUE TITLE
Interpreting Axis Order

### ISSUE THREAD

**Issue by marqh** [wmo-im/iwxxm#75]
Is there documentation and advice that TT-AvXML can provide to assist developers in this case?

I have been provided with two snippets of GML from IWXXM files

A:
```
      <gml:Point gml:id="obs-point-EGVN" uomLabels="deg deg m"
        axisLabels="Lat Lon Altitude" srsDimension="3"
        srsName="http://www.opengis.net/def/crs/EPSG/0/4979">
       <gml:pos>51.76 -1.58 81</gml:pos>
      </gml:Point>
```
B:
```
      <gml:Point gml:id="obs-point-URSS"
        srsDimension="2"
        srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
       <gml:pos>43.4445 39.9488</gml:pos>
      </gml:Point>
```
Each of these references an `srsName`, a resource available from
opengis.net
One includes `axisLabels`, but this is optional.

In case A
the `axisLabels` are "Lat Lon Altitude" and in the resource 
http://www.opengis.net/def/crs/EPSG/0/4979
the `gml:axis` instances are ordered 
"Lat Long h"

In case B
there are no axisLabels
the resource
http://www.opengis.net/def/crs/EPSG/0/4326
has two `gml:axis` elements ordered:
"Lat Long"

  1. How to advise the developers to interpret GML case A?
    - Is it "lat lon" Brize Norton?
      https://www.openstreetmap.org/search?query=51.76%20-1.58#map=10/51.7600/-1.5800
      - this is using the axisLabel ordering
    - Is it the Seychelles?
      https://www.openstreetmap.org/search?query=-1.58%2051.76#map=7/-1.582/51.757

  2. How to advise the developers to interpret GML case B?
    - Is it "lat lon": on the Russian Black Sea Coast?
      https://www.openstreetmap.org/search?query=43.4445%2039.9488#map=7/43.444/39.949
      - this is consistent with the ordering inferred from the opengis.net resource
    - Is it "lon lat": nearby in eastern Turkey?
      https://www.openstreetmap.org/search?query=39.9488%2043.4445#map=7/39.949/43.445
      - this is not inferred from any resource, but shown for completeness
  3. Is it safer to use the axisLabels, where present?
  4. Is it safer to parse the opengis.net resource and infer order?
  5. Is it necessary to resolve and parse the opengis.net resource each time, or is a local axis order lookup sufficient?

Is there documentation and advice that TT-AvXML can provide to assist developers in this case?

**Comment by dzinkhan** [comment]
Seems to be a quite well-known problem: https://wiki.osgeo.org/wiki/Axis_Order_Confusion , linked from there is an OGC doc on Axis Order Policy Guidance.
I'm not sure if it is possible to give an final answer, at least some guidance needs to be provided. For me it seems to be good idea to give the advice to encode the sequence as specified in the referenced SRS.

**Comment by braeckel** [comment]
Labels are helpful text for human readability but are not required, nor are they authoritative.  The labels are human readable and are not standardized - they may differ for every producer or even every message.  They are hints, much like the xlink:title element used with earlier versions of IWXXM.

The srsName is the essential property which indicates the SRS being used for coordinates. 
 "http://www.opengis.net/def/crs/EPSG/0/4326" is an identifier for the EPSG:4326 SRS definition (such as http://epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::4326) where the coordinate order can be found.  The link above is in Well-Known Text (WKT) format, which is a bit easier to read than the GML representation at http://www.opengis.net/def/crs/EPSG/0/4326, but they both have similar information.  

EPSG:4326 has a (latitude, longitude) coordinate order and EPSG:4979 has a (latitude, longitude, meters height above geoid) order.  EPSG:4326 and EPSG:4979 are the main CRSs used in IWXXM today and both specify a latitude then longitude order, but there are other SRSs which may specify a different order.

In short the SRS always indicates the coordinate order, and therefore the srsName is always the appropriate formal way to identify the coordinate order of each geometry.  All of the other information is ancillary, supplemental, and may be incorrect.

For the examples above the interpretations should be:

**Case A**
**SRS:** EPSG:4979 (http://epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::4979)
**Latitude:** 51.76 
**Longitude:** -1.58
**Meters height above the EPSG:4979 geoid:** 81.00
Further details on the geoid and precise geolocation are available in the EPSG:4979 SRS definition.

**Case B**
**SRS:** EPSG:4326 (http://epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::4326)
**Latitude:** 43.4445
**Longitude:** 39.9488
Further details on the geoid and precise geolocation are available in the EPSG:4326 SRS definition.

**Comment by braeckel** [comment]
This is an established and well documented trait of all GML application schemas (including AIXM and many others).  @marqh - if more information is needed we can add it here, otherwise perhaps we can close this ticket.
