### ISSUE TITLE
bulletinIdentifier format - change suggestion

### ISSUE THREAD

**Issue by mcserby** [wmo-im/iwxxm#78]
Collect examples have the bulletinIdentifier field in the format:
A_TTAAii_C_CCCC_YYYYMMddhhmmss.xml
Example:
<collect:bulletinIdentifier>A_LSYU31_C_YUSO_20120810100000.xml</collect:bulletinIdentifier>
This format matches partially the format specified in Euro DOC 33 for IWXXM transport which is:

A_TTAAiiCCCCYYGGggBBB_C_CCCC_YYYYMMddhhmmss.xml
BBB field being optional as usual.

Another option, which we currently use in bulletinIdentifier due to lack of standardization is just:
TTAAiiCCCCYYGGggBBB

That matches TAC format but of course with IWXXM product types.

Is there a reason for usage of the current format depicted in the examples? Has a formal decision been already made?

**Comment by blchoy** [comment]
Changes have been made to the examples and I would like to close this issue.
