### ISSUE TITLE
Possibly invalid METAR_SPECI.ASW1 schematron rule

### ISSUE THREAD

**Issue by mcserby** [wmo-im/iwxxm#79]
I'm using a http://phax.github.io/ph-schematron/ library for rules validation in Java.

For a metar that doesn't contain extremeClockwiseWindDirection and extremeCounterClockwiseWindDirection elements this rule evaluates for some reason to false.

If I specifically check for /@uom in exists fields, it works. Here's my modified version:

<sch:pattern id="METAR_SPECI.ASW1">
        <sch:rule context="//iwxxm:AerodromeSurfaceWind">
            <sch:assert test="(if( exists(iwxxm:meanWindDirection/@uom) and exists(iwxxm:extremeClockwiseWindDirection/@uom) and exists(iwxxm:extremeCounterClockwiseWindDirection/@uom) ) then ((iwxxm:meanWindDirection/@uom = iwxxm:extremeClockwiseWindDirection/@uom) and (iwxxm:meanWindDirection/@uom = iwxxm:extremeCounterClockwiseWindDirection/@uom)) else true())">METAR_SPECI.ASW1: All wind UOMs must be the same</sch:assert>
        </sch:rule>
    </sch:pattern>

Not sure if this is an implementation detail, I haven't checked yet other implementations yet but my modified rule might be more specific.

**Comment by blchoy** [comment]
I have no problem using OxygenXML to validate metar-a3-1.xml and the same XML document with additions of iwxxm:extremeClockwiseWindDirection and iwxxm:extremeCounterClockwiseWindDirection:

...
<iwxxm:AerodromeSurfaceWind variableWindDirection="false">
        <iwxxm:meanWindDirection uom="deg">240</iwxxm:meanWindDirection>
        <iwxxm:meanWindSpeed uom="m/s">4.0</iwxxm:meanWindSpeed>
        <iwxxm:extremeClockwiseWindDirection uom="deg">300</iwxxm:extremeClockwiseWindDirection>
        <iwxxm:extremeCounterClockwiseWindDirection uom="deg">200</iwxxm:extremeCounterClockwiseWindDirection>
    </iwxxm:AerodromeSurfaceWind>
</iwxxm:surfaceWind>
...

It would be nice if you could pass us those XML documents which failed to validate with the library you are using, or you may want to try the WMO-ICAO web validator at http://wmo-icao-validator.rap.ucar.edu/

**Comment by blchoy** [comment]
I am closing this issue as there is no further discussion on this topic.
