### ISSUE TITLE
Restructure/improve WMO wiki for IWXXM 3

### ISSUE THREAD

**Issue by braeckel** [wmo-im/iwxxm#82]
Per discussion in TT-AvXML/7:

 - Create a new IWXXM 3 wiki page
 - Restructure the tutorials to reduce duplication to make it easier to maintain.  Improve focus on individual features being introduced in IWXXM 3, and focus on specific IWXXM aspects rather than on full example-based descriptions
 - Add some content related to transition guidance from IWXXM 2 to IWXXM 3
 - Document guidance on the use of COLLECT with IWXXM messages (see details below, originally discussed in #66). The goal would be that IWXXM messages not change during the COLLECT/de-COLLECT process so they can be identified downstream

**Comment by blchoy** [comment]
With the retiring of the wiswiki (#218) this issue has been superseded by event and is hereby closed.
