### ISSUE TITLE
Sigmet example in 2.1.1: TAC and XML do not correspond

### ISSUE THREAD

**Issue by ernstdevreede** [wmo-im/iwxxm#92]
In the examples for version 2.1.1  in the SIGMET example sigmet-A6-1a-TS a SIGMET is used which shows movement speed and direction together with a end position description of the phenomenon geometry. It is my understanding that a SIGMET should only use one of thes: either movement info or an end position.
The XML version of the same example only has an analysis element with a movement speed and direction, but no  ForecastPositionAnalysis element. The comments in sigmet-A6-1a-TS.xml do however show a TAC source without an end position description.

So I see 2 possible issues here:
* the XML version of sigmet-A6-1a-TS is not based on the contents of sigmet-A6-1a-TS.tac
* the contents of sigmet-A6-1a-TS.tac are not (currently) valid, because it contains movement and an end position (ForecastPositionAnalysis)

**Comment by braeckel** [comment]
Hi @ernstdevreede, we recently removed the .tac examples for this and other reasons from the [3.0RC1 baseline](https://github.com/wmo-im/iwxxm/tree/master/3.0.0RC1/examples).  In general the TAC embedded in the .xml files have been kept up to date and the .tac files have unfortunately languished.  Therefore the TAC in .xml files should be considered authoritative and the .tac files may safely be ignored.

Does this address all of your questions?

**Comment by ernstdevreede** [comment]
Hi @braeckel. Your response addresses my questions. I will stop looking at the sometimes confusing TAC messages in the examples.
