### ISSUE TITLE
IWXXM 3.0.0RC1 METAR NOSIG issue

### ISSUE THREAD

**Issue by mgoberfield** [wmo-im/iwxxm#99]
When NOSIG appears in the METAR TAC, oXygen validation flags the use of nilReason in iwxxm:trendForecast element. (I have downloaded the latest version of the schema on 30 July 2018.)
This is in disagreement with the TAC-to-XML-Guidance.txt document.

![trendforecast](https://user-images.githubusercontent.com/7852621/43420527-832f2738-9433-11e8-843f-64dee7b93e89.png)

**Comment by blchoy** [comment]
Thanks for pointing out.  This is due to an EA transformation error which slip through my eyes.  Anyway I have committed a revised update to the master branch and affected files on schemas.wmo.int will also be updated asap.
